plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.turnikcoach.app'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId 'ru.turnikcoach.app'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0.0-trial'
    }
}
