package ru.matchstats.app;

import android.app.Activity;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;

public class MainActivity extends Activity {
  static final String API="https://api.sofascore.com/api/v1", WEB="https://www.sofascore.com/api/v1";
  static final int BG=Color.rgb(10,15,20), C=Color.rgb(20,28,36), C2=Color.rgb(26,36,46), T=Color.rgb(240,244,247), M=Color.rgb(145,157,169), G=Color.rgb(38,166,91), A=Color.rgb(64,145,255), R=Color.rgb(220,80,80), Y=Color.rgb(225,155,45);
  final ExecutorService io=Executors.newFixedThreadPool(4); final AtomicBoolean busy=new AtomicBoolean(false);
  final List<Match> line=new ArrayList<>(), live=new ArrayList<>(); boolean liveMode=false; String status="Загрузка событий…";

  @Override public void onCreate(Bundle b){super.onCreate(b);render();load(false);} @Override public void onDestroy(){io.shutdownNow();super.onDestroy();}

  void load(boolean isLive){
    if(!busy.compareAndSet(false,true))return; status=isLive?"Обновление LIVE…":"Загрузка линии…"; render();
    io.execute(()->{ List<Match> out=new ArrayList<>(); String err=""; try{out=isLive?loadLive():loadLine();}catch(Exception e){err=msg(e);} final List<Match> r=out; final String er=err;
      runOnUiThread(()->{List<Match> dst=isLive?live:line;dst.clear();dst.addAll(r);status=r.isEmpty()?(!er.isEmpty()?er:(isLive?"Сейчас нет матчей LIVE":"Будущие матчи не получены")):(isLive?"LIVE: ":"ЛИНИЯ: ")+r.size()+" матчей";busy.set(false);render();});});
  }

  List<Match> loadLine()throws Exception{
    JSONObject root=get(API+"/sport/football/scheduled-events/"+today()); JSONArray ev=root.optJSONArray("events"); List<Match> out=new ArrayList<>(); if(ev==null)return out; long now=System.currentTimeMillis()/1000;
    for(int i=0;i<ev.length()&&out.size()<50;i++){JSONObject e=ev.optJSONObject(i);if(e==null)continue;JSONObject s=e.optJSONObject("status");String type=s==null?"":s.optString("type","");if(!("notstarted".equals(type)||"scheduled".equals(type)))continue;Match m=parse(e,false);if(m==null||(m.ts>0&&m.ts<now-60))continue;pregame(m);calc(m,false);out.add(m);}return out;
  }

  List<Match> loadLive()throws Exception{
    JSONObject root; try{root=get(WEB+"/sport/football/events/live");}catch(Exception e1){try{root=get(API+"/sport/football/events/live");}catch(Exception e2){throw new Exception("SofaScore LIVE: "+msg(e1)+" / "+msg(e2));}}
    JSONArray ev=root.optJSONArray("events");List<Match> out=new ArrayList<>();if(ev==null)return out;
    for(int i=0;i<ev.length()&&out.size()<50;i++){JSONObject e=ev.optJSONObject(i);if(e==null)continue;JSONObject s=e.optJSONObject("status");String type=s==null?"":s.optString("type","");if("finished".equals(type)||"canceled".equals(type)||"postponed".equals(type))continue;Match m=parse(e,true);if(m==null)continue;pregame(m);try{stats(m,get(API+"/event/"+m.id+"/statistics"));}catch(Exception ignored){}calc(m,true);out.add(m);}return out;
  }

  Match parse(JSONObject e,boolean isLive){
    JSONObject h=e.optJSONObject("homeTeam"),a=e.optJSONObject("awayTeam");long id=e.optLong("id",-1);if(id<0||h==null||a==null)return null;Match m=new Match();m.id=id;m.h=h.optString("name","—");m.a=a.optString("name","—");m.ts=e.optLong("startTimestamp",0);
    JSONObject tr=e.optJSONObject("tournament"),cat=tr==null?null:tr.optJSONObject("category");String lg=tr==null?"Футбол":tr.optString("name","Футбол"),co=cat==null?"":cat.optString("name","");m.league=co.isEmpty()?lg:co+" · "+lg;
    JSONObject hs=e.optJSONObject("homeScore"),as=e.optJSONObject("awayScore");m.hg=hs==null?-1:hs.optInt("current",-1);m.ag=as==null?-1:as.optInt("current",-1);m.h1g=hs==null?-1:hs.optInt("period1",-1);m.a1g=as==null?-1:as.optInt("period1",-1);
    if(isLive){JSONObject st=e.optJSONObject("status"),tm=e.optJSONObject("time");String p=st==null?"":st.optString("period","");long start=tm==null?0:tm.optLong("currentPeriodStartTimestamp",0);if(start>0){int el=(int)Math.max(0,(System.currentTimeMillis()/1000-start)/60);m.min=p.contains("2")?45+el:el;}if(m.min<=0&&st!=null)m.min=st.optInt("elapsed",0);}return m;
  }

  void pregame(Match m){try{JSONObject r=get(API+"/event/"+m.id+"/pregame-form"),h=r.optJSONObject("homeTeam"),a=r.optJSONObject("awayTeam");if(h!=null&&a!=null){m.hs=strength(h,true);m.as=strength(a,false);}}catch(Exception ignored){}}
  double strength(JSONObject t,boolean home){JSONArray f=t.optJSONArray("form");double pts=0;int n=0;if(f!=null)for(int i=0;i<f.length();i++){String x=f.optString(i,"");pts+="W".equalsIgnoreCase(x)?3:"D".equalsIgnoreCase(x)?1:0;n++;}double form=n>0?pts/(3*n):.5;int pos=t.optInt("position",0);double ps=pos>0?clamp(1-(pos-1)/19.0,0,1):.5;return clamp(.7*form+.3*ps+(home?.035:0),.08,.92);}

  void stats(Match m,JSONObject r){JSONArray ps=r.optJSONArray("statistics");if(ps==null)return;for(int i=0;i<ps.length();i++){JSONObject p=ps.optJSONObject(i);if(p==null||!"ALL".equals(p.optString("period","") ))continue;JSONArray gs=p.optJSONArray("groups");if(gs==null)continue;for(int g=0;g<gs.length();g++){JSONObject gr=gs.optJSONObject(g);JSONArray it=gr==null?null:gr.optJSONArray("statisticsItems");if(it==null)continue;for(int k=0;k<it.length();k++){JSONObject x=it.optJSONObject(k);if(x==null)continue;String key=x.optString("key",""),val=x.optString("home","—")+" — "+x.optString("away","—");double hv=sv(x,"home"),av=sv(x,"away");if("ballPossession".equals(key)){m.pos=val;m.ph=hv;m.pa=av;}if("shotsOnGoal".equals(key)){m.sot=val;m.sh=hv;m.sa=av;}if("totalShots".equals(key)){m.shots=val;m.th=hv;m.ta=av;}if(key.toLowerCase(Locale.ROOT).contains("expectedgoals")){m.xg=val;m.xh=hv;m.xa=av;}}}}}
  double sv(JSONObject o,String s){double v=o.optDouble(s+"Value",Double.NaN);if(!Double.isNaN(v))return v;try{return Double.parseDouble(o.optString(s,"0").replace("%","").replace(',','.'));}catch(Exception e){return 0;}}

  void calc(Match m,boolean isLive){double d=m.hs-m.as,lh=clamp(1.42+1.05*d,.45,2.65),la=clamp(1.14-.90*d,.35,2.45);if(isLive){double rem=clamp((90-m.min)/90.0,0,1),p=0;if(m.xh+m.xa>0)p+=.34*(m.xh-m.xa);if(m.sh+m.sa>0)p+=.055*(m.sh-m.sa);if(m.th+m.ta>0)p+=.018*(m.th-m.ta);if(m.ph+m.pa>0)p+=.004*(m.ph-m.pa);p=clamp(p,-.75,.75);double rh=clamp(lh*rem*(1+p),.02,2.8),ra=clamp(la*rem*(1-p),.02,2.8);int hg=Math.max(0,m.hg),ag=Math.max(0,m.ag);outcome(m,hg,ag,rh,ra,false);totals(m,hg+ag,rh+ra);if(m.min<=45){double hr=clamp((45-m.min)/45.0,0,1);double hh=clamp(lh*.46*hr*(1+p),.01,1.8),ha=clamp(la*.46*hr*(1-p),.01,1.8);outcome(m,hg,ag,hh,ha,true);halfTotals(m,hg+ag,hh+ha);}else if(m.h1g>=0&&m.a1g>=0)doneHalf(m);}else{outcome(m,0,0,lh,la,false);totals(m,0,lh+la);outcome(m,0,0,lh*.46,la*.46,true);halfTotals(m,0,(lh+la)*.46);}}
  void outcome(Match m,int bh,int ba,double lh,double la,boolean half){double p1=0,px=0,p2=0;for(int h=0;h<10;h++)for(int a=0;a<10;a++){double p=poi(h,lh)*poi(a,la);if(bh+h>ba+a)p1+=p;else if(bh+h==ba+a)px+=p;else p2+=p;}double s=p1+px+p2;if(s<=0)return;int a=(int)Math.round(p1/s*100),b=(int)Math.round(px/s*100),c=100-a-b;if(half){m.h1p1=a;m.h1px=b;m.h1p2=c;}else{m.p1=a;m.px=b;m.p2=c;}}
  void totals(Match m,int g,double l){m.o15=over(g,l,1);m.u15=100-m.o15;m.o25=over(g,l,2);m.u25=100-m.o25;} void halfTotals(Match m,int g,double l){m.ho05=over(g,l,0);m.hu05=100-m.ho05;m.ho15=over(g,l,1);m.hu15=100-m.ho15;} void doneHalf(Match m){int h=m.h1g,a=m.a1g;m.h1p1=h>a?100:0;m.h1px=h==a?100:0;m.h1p2=h<a?100:0;int g=h+a;m.ho05=g>0?100:0;m.hu05=100-m.ho05;m.ho15=g>1?100:0;m.hu15=100-m.ho15;}
  int over(int current,double l,int t){if(current>t)return 100;double p=0;for(int i=0;i<12;i++)if(current+i>t)p+=poi(i,l);return(int)Math.round(clamp(p,0,1)*100);} double poi(int k,double l){double f=1;for(int i=2;i<=k;i++)f*=i;return Math.exp(-l)*Math.pow(l,k)/f;} double clamp(double v,double lo,double hi){return Math.max(lo,Math.min(hi,v));}

  JSONObject get(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(12000);c.setInstanceFollowRedirects(true);c.setRequestProperty("Accept","application/json, text/plain, */*");c.setRequestProperty("Accept-Language","en-US,en;q=0.9");c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 16; Mobile) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36");c.setRequestProperty("Referer","https://www.sofascore.com/");c.setRequestProperty("Origin","https://www.sofascore.com");c.setRequestProperty("Sec-Fetch-Site","same-site");c.setRequestProperty("Sec-Fetch-Mode","cors");c.setRequestProperty("Sec-Fetch-Dest","empty");int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String body=read(is);c.disconnect();if(code<200||code>=300)throw new Exception("SofaScore: HTTP "+code+" · "+host(url));if(body.trim().isEmpty())throw new Exception("SofaScore: пустой ответ");return new JSONObject(body);} String read(InputStream is)throws Exception{if(is==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(is));StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s);r.close();return b.toString();} String host(String u){try{return new URL(u).getHost();}catch(Exception e){return u;}} String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();} String today(){SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.US);f.setTimeZone(TimeZone.getDefault());return f.format(new Date());}

  void render(){LinearLayout root=v();root.setBackgroundColor(BG);root.setPadding(dp(14),dp(12),dp(14),dp(12));root.addView(txt("DENZL",26,T,true));TextView sub=txt("Вероятность DENZL · без коэффициентов",12,M,false);sub.setPadding(0,0,0,dp(10));root.addView(sub);LinearLayout tabs=new LinearLayout(this);tabs.setWeightSum(2);Button lb=tab("ЛИНИЯ",!liveMode),lv=tab("LIVE",liveMode);tabs.addView(lb,new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(lv,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(tabs);lb.setOnClickListener(x->{liveMode=false;load(false);});lv.setOnClickListener(x->{liveMode=true;load(true);});if(liveMode){Button r=new Button(this);r.setText(busy.get()?"ОБНОВЛЕНИЕ…":"ОБНОВИТЬ LIVE");r.setEnabled(!busy.get());r.setTextColor(Color.WHITE);r.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.setBackground(box(A,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(46));p.setMargins(0,dp(8),0,0);root.addView(r,p);r.setOnClickListener(x->load(true));}boolean er=status.contains("HTTP")||status.toLowerCase(Locale.ROOT).contains("недоступ");TextView s=txt(status,12,busy.get()?A:(er?R:G),true);s.setGravity(Gravity.CENTER);s.setPadding(0,dp(8),0,dp(2));root.addView(s);ScrollView sc=new ScrollView(this);LinearLayout list=v();for(Match m:(liveMode?live:line))list.addView(card(m));sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(txt("Без API-ключей и без коэффициентов. LIVE обновляется вручную.",10,M,false));setContentView(root);}
  View card(Match m){LinearLayout c=v();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(box(C,16));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(9),0,0);c.setLayoutParams(cp);LinearLayout top=new LinearLayout(this);top.addView(txt(m.league,11,M,false),new LinearLayout.LayoutParams(0,-2,1));String tm=m.min>0?m.min+"'":time(m.ts);top.addView(txt(tm+(m.min>=80?" · ПОЗДНИЙ LIVE":""),11,m.min>=80?Y:(m.min>0?G:M),true));c.addView(top);String score=m.hg>=0&&m.ag>=0?"   "+m.hg+":"+m.ag:"";TextView teams=txt(m.h+" — "+m.a+score,17,T,true);teams.setPadding(0,dp(7),0,dp(8));c.addView(teams);LinearLayout tabs=new LinearLayout(this);tabs.setWeightSum(2);Button full=small("МАТЧ",true),first=small("1-Й ТАЙМ",false);tabs.addView(full,new LinearLayout.LayoutParams(0,dp(40),1));tabs.addView(first,new LinearLayout.LayoutParams(0,dp(40),1));c.addView(tabs);LinearLayout host=v();host.addView(fullM(m));c.addView(host);full.setOnClickListener(x->{host.removeAllViews();host.addView(fullM(m));full.setBackground(box(A,10));first.setBackground(box(C2,10));});first.setOnClickListener(x->{host.removeAllViews();host.addView(firstM(m));first.setBackground(box(A,10));full.setBackground(box(C2,10));});TextView det=txt("Статистика",13,A,true);det.setGravity(Gravity.CENTER);det.setPadding(0,dp(10),0,dp(3));c.addView(det);det.setOnClickListener(x->toggle(c,det,m));return c;}
  View fullM(Match m){LinearLayout b=v();b.setPadding(0,dp(8),0,0);b.addView(out(m.p1,m.px,m.p2));total(b,"ТОТАЛ 2.5","ТБ 2.5",m.o25,"ТМ 2.5",m.u25);total(b,"ТОТАЛ 1.5","ТБ 1.5",m.o15,"ТМ 1.5",m.u15);return b;} View firstM(Match m){LinearLayout b=v();b.setPadding(0,dp(8),0,0);b.addView(out(m.h1p1,m.h1px,m.h1p2));total(b,"1-Й ТАЙМ · ТОТАЛ 0.5","ТБ 0.5",m.ho05,"ТМ 0.5",m.hu05);total(b,"1-Й ТАЙМ · ТОТАЛ 1.5","ТБ 1.5",m.ho15,"ТМ 1.5",m.hu15);return b;}
  View out(int a,int b,int c){LinearLayout r=new LinearLayout(this);r.setWeightSum(3);r.addView(pb("П1",a,false),new LinearLayout.LayoutParams(0,dp(66),1));r.addView(pb("X",b,false),new LinearLayout.LayoutParams(0,dp(66),1));r.addView(pb("П2",c,false),new LinearLayout.LayoutParams(0,dp(66),1));return r;} void total(LinearLayout p,String title,String l,int lp,String rr,int rp){TextView t=txt(title,11,M,true);t.setPadding(0,dp(10),0,dp(4));p.addView(t);LinearLayout r=new LinearLayout(this);r.setWeightSum(2);r.addView(pb(l,lp,lp>=58&&lp>rp),new LinearLayout.LayoutParams(0,dp(66),1));r.addView(pb(rr,rp,rp>=58&&rp>lp),new LinearLayout.LayoutParams(0,dp(66),1));p.addView(r);} View pb(String l,int p,boolean hi){LinearLayout b=v();b.setGravity(Gravity.CENTER);b.setBackground(box(hi?G:C2,11));b.addView(txt(l,12,hi?Color.WHITE:M,true));b.addView(txt(p<0?"—":p+"%",17,Color.WHITE,true));return b;}
  void toggle(LinearLayout c,TextView ctl,Match m){Object tag=ctl.getTag();if(tag instanceof View){c.removeView((View)tag);ctl.setTag(null);return;}LinearLayout b=v();b.setPadding(dp(10),dp(8),dp(10),dp(8));b.setBackground(box(C2,10));b.addView(stat("Удары",m.shots));b.addView(stat("В створ",m.sot));b.addView(stat("Владение",m.pos));b.addView(stat("xG",m.xg));c.addView(b);ctl.setTag(b);} View stat(String a,String b){LinearLayout r=new LinearLayout(this);r.addView(txt(a,12,M,false),new LinearLayout.LayoutParams(0,-2,1));r.addView(txt(b==null?"—":b,12,T,true));return r;}
  String time(long ts){if(ts<=0)return"—";return new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(ts*1000));} LinearLayout v(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} Button tab(String s,boolean on){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(box(on?A:C,12));return b;} Button small(String s,boolean on){Button b=tab(s,on);b.setTextSize(12);return b;} TextView txt(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;} GradientDrawable box(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;} int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}

  static class Match{long id=-1,ts;String league="Футбол",h="—",a="—",shots="—",sot="—",pos="—",xg="—";int min=0,hg=-1,ag=-1,h1g=-1,a1g=-1;double hs=.54,as=.46,th,ta,sh,sa,ph,pa,xh,xa;int p1=-1,px=-1,p2=-1,o25=-1,u25=-1,o15=-1,u15=-1,h1p1=-1,h1px=-1,h1p2=-1,ho05=-1,hu05=-1,ho15=-1,hu15=-1;}
}
