package ru.matchstats.app;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

public class MainActivity extends Activity {
    private static final String BC_PRE="https://ad.betcity.ru/d/off/events?id_sp=1&ch_id=0&gr_id=0&add=main,ext,name_sp,name_ch&rev=2&ver=69&csn=ooca9s";
    private static final String[] BC_LIVE={
            "https://ad.betcity.ru/d/on_air/bets?id_sp=1&rev=8&add=dep_event,name_sp,name_ch&template=1&ver=69&csn=ooca9s",
            "https://ad.betcity.ru/d/on_air/bets?id_sp=1&rev=2&add=name_sp,name_ch&template=1&ver=69&csn=ooca9s"};
    private static final String SOFA="https://api.sofascore.com/api/v1";
    private static final String FOT="https://www.fotmob.com/api/data";

    private static final int BG=Color.rgb(10,15,20),CARD=Color.rgb(20,28,36),CARD2=Color.rgb(26,36,46),TEXT=Color.rgb(240,244,247),MUTED=Color.rgb(145,157,169),GREEN=Color.rgb(38,166,91),ACCENT=Color.rgb(64,145,255),RED=Color.rgb(220,80,80),AMBER=Color.rgb(225,155,45);
    private final ExecutorService io=Executors.newFixedThreadPool(5);
    private final AtomicBoolean busy=new AtomicBoolean(false);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final List<Match> results=new ArrayList<>();
    private final Map<String,Profile> cache=new LinkedHashMap<>();
    private boolean liveMode=false;
    private String query="",status="Введите команду или лигу и нажмите НАЙТИ";
    private long lineCacheAt=0; private JSONObject lineCache,liveCache;

    @Override public void onCreate(Bundle b){super.onCreate(b);render();}
    @Override public void onDestroy(){handler.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}

    private final Runnable liveTick=new Runnable(){@Override public void run(){if(liveMode&&!query.isEmpty()){search(query,true);handler.postDelayed(this,30000);}}};
    private void startLive(){handler.removeCallbacks(liveTick);handler.postDelayed(liveTick,30000);} private void stopLive(){handler.removeCallbacks(liveTick);}

    private void search(String q,boolean live){
        q=q==null?"":q.trim(); if(q.length()<2){status="Введите не менее 2 символов";render();return;} query=q;
        if(!busy.compareAndSet(false,true))return; status="Поиск в "+(live?"LIVE":"линии")+" BETCITY…";render();
        final String fq=q;io.execute(()->{List<Match> found=new ArrayList<>();String err="";try{JSONObject root=loadBetcityRoot(live);walkBetcity(root,"",-1,"",live,fq,found);Collections.sort(found,(a,b)->Long.compare(a.ts,b.ts));}catch(Exception e){err=msg(e);}final List<Match> out=found;final String er=err;runOnUiThread(()->{results.clear();results.addAll(out);status=out.isEmpty()?(!er.isEmpty()?er:"Совпадений среди футбольных матчей BETCITY нет"):("Найдено: "+out.size()+" · только футбол 11×11");busy.set(false);render();});});
    }

    private JSONObject loadBetcityRoot(boolean live)throws Exception{
        long now=System.currentTimeMillis();
        if(!live&&lineCache!=null&&now-lineCacheAt<60000)return lineCache;
        if(live){Exception last=null;for(String u:BC_LIVE)try{JSONObject x=getJson(u,"https://betcity.ru/ru/live/football");liveCache=x;return x;}catch(Exception e){last=e;}if(last!=null)throw last;}
        JSONObject x=getJson(BC_PRE,"https://betcity.ru/ru/line/football");lineCache=x;lineCacheAt=now;return x;
    }

    private void walkBetcity(Object node,String league,int sportId,String sportName,boolean live,String q,List<Match> out){
        if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String nextLeague=league,nextSport=sportName;int nextId=sportId;
            if(o.has("name_ch"))nextLeague=o.optString("name_ch",league); if(o.has("name_sp"))nextSport=o.optString("name_sp",sportName); if(o.has("id_sp"))nextId=o.optInt("id_sp",sportId);
            if(o.has("id_ev")&&o.has("name_ht")&&o.has("name_at")){
                boolean football=nextId==1||isFootballName(nextSport); if(football){Match m=parseEvent(o,nextLeague,live);if(m!=null&&matchesQuery(m,q))out.add(m);}
            }
            Iterator<String> it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkBetcity(v,nextLeague,nextId,nextSport,live,q,out);}
        }else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkBetcity(v,league,sportId,sportName,live,q,out);}}
    }

    private boolean isFootballName(String s){String x=s==null?"":s.toLowerCase(Locale.ROOT);return x.equals("football")||x.equals("soccer")||x.contains("футбол");}
    private boolean matchesQuery(Match m,String q){String k=norm(q),all=norm(m.home+" "+m.away+" "+m.league+" "+m.country);return all.contains(k)||tokenHit(all,k);}
    private boolean tokenHit(String all,String q){for(String t:q.split(" "))if(t.length()>2&&!all.contains(t))return false;return true;}
    private Match parseEvent(JSONObject e,String league,boolean live){String h=e.optString("name_ht","").trim(),a=e.optString("name_at","").trim(),l=cleanLeague(league);if(h.length()<2||a.length()<2||excluded(l+" "+h+" "+a))return null;if(!live&&truth(e.opt("is_live")))return null;Match m=new Match();m.id=String.valueOf(e.optLong("id_ev",e.optInt("id_ev",0)));m.home=h;m.away=a;m.league=l;m.country=country(l);m.ts=parseDate(e.opt("date_ev"));parseScore(e.optString("sc_ev",""),m,false);parseScore(e.optString("sc_ext_ev",""),m,true);m.min=findMinute(e);scanMarkets(e,m,"");scanStats(e,m);return m;}
    private boolean excluded(String s){String x=(s==null?"":s).toLowerCase(Locale.ROOT).replace('×','x');String[] bad={"3x3","4x4","5x5","6x6","7x7","8x8","3 х 3","4 х 4","5 х 5","6 х 6","7 х 7","8 х 8","futsal","футзал","мини-футбол","мини футбол","mini football","indoor","cyber","кибер","esport","e-sport","virtual","виртуал","penalty shootout","серия пенальти"};for(String b:bad)if(x.contains(b))return true;return false;}

    private void analyze(Match m){if(m.loading)return;m.loading=true;m.error="";status="Собираю статистику "+m.home+" и "+m.away+"…";render();io.execute(()->{try{Profile h=getProfile(m.home),a=getProfile(m.away);m.ph=h;m.pa=a;calculate(m);}catch(Exception e){m.error=msg(e);}m.loading=false;runOnUiThread(()->{status=m.error.isEmpty()?"Статистика рассчитана: SofaScore / FotMob":"Статистика: "+m.error;render();});});}

    private Profile getProfile(String name)throws Exception{String k=norm(name);Profile c=cache.get(k);if(c!=null&&System.currentTimeMillis()-c.loadedAt<3600000)return c;Profile p=null;Exception last=null;try{p=sofaProfile(name);}catch(Exception e){last=e;}if(p==null||p.n<5){try{Profile f=fotmobProfile(name);if(f!=null&&(p==null||f.n>p.n))p=f;}catch(Exception e){last=e;}}if(p==null)throw last!=null?last:new Exception("нет истории команды");p.loadedAt=System.currentTimeMillis();cache.put(k,p);return p;}

    private Profile sofaProfile(String name)throws Exception{JSONObject sr=getJson(SOFA+"/search/all?q="+enc(name),"https://www.sofascore.com/");int teamId=findSofaTeam(sr,name);if(teamId<=0)throw new Exception("SofaScore: команда не найдена");Profile p=new Profile();p.source="SofaScore";List<Hist> events=new ArrayList<>();for(int page=0;page<2&&events.size()<20;page++){JSONObject root=getJson(SOFA+"/team/"+teamId+"/events/last/"+page,"https://www.sofascore.com/");JSONArray ar=root.optJSONArray("events");if(ar==null)break;for(int i=0;i<ar.length()&&events.size()<20;i++){Hist h=parseSofaEvent(ar.optJSONObject(i),teamId);if(h!=null)events.add(h);}}
        for(Hist h:events){p.addResult(h);if(p.statN<8&&h.eventId>0)try{JSONObject st=getJson(SOFA+"/event/"+h.eventId+"/statistics","https://www.sofascore.com/");addSofaStats(st,p,h.teamHome);}catch(Exception ignored){}}
        return p;}
    private int findSofaTeam(Object node,String name){int[] best={0,-1};walkFindTeam(node,name,best);return best[0];}
    private void walkFindTeam(Object node,String name,int[] best){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;JSONObject ent=o.optJSONObject("entity");if(ent!=null){String n=ent.optString("name","");String type=o.optString("type",ent.optString("entityType",""));JSONObject sport=ent.optJSONObject("sport");String slug=sport==null?"":sport.optString("slug","");if(("team".equalsIgnoreCase(type)||"team".equalsIgnoreCase(ent.optString("entityType","")))&&(slug.isEmpty()||slug.equals("football"))){int sc=similarity(name,n);if(sc>best[1]){best[0]=ent.optInt("id",0);best[1]=sc;}}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkFindTeam(v,name,best);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkFindTeam(v,name,best);}}}
    private Hist parseSofaEvent(JSONObject e,int teamId){if(e==null)return null;JSONObject ht=e.optJSONObject("homeTeam"),at=e.optJSONObject("awayTeam"),hs=e.optJSONObject("homeScore"),as=e.optJSONObject("awayScore");if(ht==null||at==null||hs==null||as==null)return null;boolean home=ht.optInt("id")==teamId;if(!home&&at.optInt("id")!=teamId)return null;int hg=scoreVal(hs),ag=scoreVal(as);if(hg<0||ag<0)return null;Hist h=new Hist();h.eventId=e.optInt("id",0);h.teamHome=home;h.gf=home?hg:ag;h.ga=home?ag:hg;h.h1gf=home?period1(hs):period1(as);h.h1ga=home?period1(as):period1(hs);return h;}
    private int scoreVal(JSONObject s){if(s==null)return-1;if(s.has("normaltime"))return s.optInt("normaltime",-1);if(s.has("current"))return s.optInt("current",-1);return-1;}private int period1(JSONObject s){return s==null?-1:s.optInt("period1",-1);}
    private void addSofaStats(Object node,Profile p,boolean teamHome){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;if(o.has("name")&&o.has("home")&&o.has("away")){String n=o.optString("name","").toLowerCase(Locale.ROOT);double hv=num(o.opt("home")),av=num(o.opt("away")),f=teamHome?hv:av,a=teamHome?av:hv;if(n.contains("expected goals")||n.equals("xg")){p.xgF+=f;p.xgA+=a;p.xgN++;}else if(n.contains("shots on target")||n.contains("в створ")){p.sotF+=f;p.sotA+=a;p.sotN++;}else if(n.equals("total shots")||n.contains("total shots")||n.equals("shots")){p.shF+=f;p.shA+=a;p.shN++;}else if(n.contains("ball possession")||n.contains("possession")){p.posF+=f;p.posA+=a;p.posN++;}else if(n.contains("corner")){p.corF+=f;p.corA+=a;p.corN++;}else if(n.contains("yellow card")){p.cardF+=f;p.cardA+=a;p.cardN++;}}
            Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)addSofaStats(v,p,teamHome);}
        }else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)addSofaStats(v,p,teamHome);}}p.statN=Math.max(p.statN,Math.max(p.xgN,Math.max(p.sotN,p.shN)));}

    private Profile fotmobProfile(String name)throws Exception{JSONObject sr=getJson(FOT+"/search/suggest?hits=20&lang=en&term="+enc(name),"https://www.fotmob.com/");int id=findFotTeam(sr,name);if(id<=0)throw new Exception("FotMob: команда не найдена");JSONObject tr=getJson(FOT+"/teams?id="+id,"https://www.fotmob.com/");Profile p=new Profile();p.source="FotMob";walkFotMatches(tr,id,p);return p;}
    private int findFotTeam(Object node,String name){int[]best={0,-1};walkFotTeam(node,name,best);return best[0];}
    private void walkFotTeam(Object node,String name,int[]best){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String n=o.optString("name",o.optString("title","")),type=o.optString("type",o.optString("suggestionType",""));int id=o.optInt("id",o.optInt("teamId",0));if(id>0&&!n.isEmpty()&&(type.toLowerCase(Locale.ROOT).contains("team")||o.has("teamId"))){int s=similarity(name,n);if(s>best[1]){best[0]=id;best[1]=s;}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkFotTeam(v,name,best);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkFotTeam(v,name,best);}}}
    private void walkFotMatches(Object node,int teamId,Profile p){if(p.n>=20)return;if(node instanceof JSONObject){JSONObject o=(JSONObject)node,home=o.optJSONObject("home"),away=o.optJSONObject("away");if(home!=null&&away!=null){int hid=home.optInt("id",0),aid=away.optInt("id",0);if(hid==teamId||aid==teamId){String score="";JSONObject st=o.optJSONObject("status");if(st!=null)score=st.optString("scoreStr","");int[]sc=parsePairScore(score);if(sc!=null){Hist h=new Hist();h.teamHome=hid==teamId;h.gf=h.teamHome?sc[0]:sc[1];h.ga=h.teamHome?sc[1]:sc[0];p.addResult(h);}}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkFotMatches(v,teamId,p);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length()&&p.n<20;i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkFotMatches(v,teamId,p);}}}

    private void calculate(Match m){Profile h=m.ph,a=m.pa;m.criteria.clear();double totalW=0,usedW=0,sp1=0,sx=0,sp2=0,slh=0,sla=0;
        totalW+=addC(m,"Форма последних матчей",h.n>=5&&a.n>=5,1.2,1.25*(.72+h.form()),1.05*(.72+a.form()),h.n+" / "+a.n+" матчей");
        totalW+=addC(m,"Голы: атака / оборона",h.n>=5&&a.n>=5,2.0,clamp((h.gf()+a.ga())/2*1.08,.25,3.3),clamp((a.gf()+h.ga())/2*.94,.20,3.0),String.format(Locale.US,"GF/GA %.2f/%.2f · %.2f/%.2f",h.gf(),h.ga(),a.gf(),a.ga()));
        totalW+=addC(m,"Дом / выезд",h.homeN>=3&&a.awayN>=3,1.4,clamp((h.homeGF()+a.awayGA())/2,.25,3.3),clamp((a.awayGF()+h.homeGA())/2,.20,3.0),h.homeN+" дом · "+a.awayN+" выезд");
        totalW+=addC(m,"xG / xGA",h.xgN>=3&&a.xgN>=3,2.2,clamp((h.xgF()+a.xgA())/2,.20,3.4),clamp((a.xgF()+h.xgA())/2,.20,3.2),h.xgN+" / "+a.xgN+" матчей");
        totalW+=addDiffC(m,"Удары в створ",h.sotN>=3&&a.sotN>=3,1.5,h.sotF()-h.sotA(),a.sotF()-a.sotA(),"ср. "+fmt(h.sotF())+" / "+fmt(a.sotF()));
        totalW+=addDiffC(m,"Удары",h.shN>=3&&a.shN>=3,1.0,h.shF()-h.shA(),a.shF()-a.shA(),"ср. "+fmt(h.shF())+" / "+fmt(a.shF()));
        totalW+=addDiffC(m,"Угловые",h.corN>=3&&a.corN>=3,.55,h.corF()-h.corA(),a.corF()-a.corA(),"ср. "+fmt(h.corF())+" / "+fmt(a.corF()));
        totalW+=addDiffC(m,"Владение",h.posN>=3&&a.posN>=3,.35,(h.posF()-50)/10,(a.posF()-50)/10,"ср. "+fmt(h.posF())+"% / "+fmt(a.posF())+"%");
        totalW+=addDiffC(m,"Карточки",h.cardN>=3&&a.cardN>=3,.25,-(h.cardF()-h.cardA()),-(a.cardF()-a.cardA()),"ср. "+fmt(h.cardF())+" / "+fmt(a.cardF()));
        for(Criterion c:m.criteria)if(c.available){usedW+=c.w;sp1+=c.p1*c.w;sx+=c.px*c.w;sp2+=c.p2*c.w;slh+=c.lh*c.w;sla+=c.la*c.w;}
        double sample=Math.min(1,Math.min(h.n,a.n)/10.0),coverage=totalW>0?usedW/totalW:0;m.reliability=(int)Math.round(100*(.72*coverage+.28*sample));
        if(usedW<=0||m.reliability<45||h.n<5||a.n<5){m.p1=m.px=m.p2=-1;m.ready=false;return;}
        int p1=(int)Math.round(sp1/usedW),px=(int)Math.round(sx/usedW);m.p1=p1;m.px=px;m.p2=Math.max(0,100-p1-px);m.lambdaH=slh/usedW;m.lambdaA=sla/usedW;m.ready=true;
        double lt=m.lambdaH+m.lambdaA;m.o15=atLeast(lt,2);m.u15=100-m.o15;m.o25=atLeast(lt,3);m.u25=100-m.o25;m.bttsYes=(int)Math.round((1-Math.exp(-m.lambdaH))*(1-Math.exp(-m.lambdaA))*100);m.bttsNo=100-m.bttsYes;
        double h1=h.h1N>=4?clamp((h.h1gf()+a.h1ga())/2,.15,1.7):m.lambdaH*.46,doubleA=a.h1N>=4?clamp((a.h1gf()+h.h1ga())/2,.10,1.5):m.lambdaA*.46;int[]hp=outcomeArray(0,0,h1,doubleA);m.h1p1=hp[0];m.h1px=hp[1];m.h1p2=hp[2];double hlt=h1+doubleA;m.ho05=atLeast(hlt,1);m.hu05=100-m.ho05;m.ho15=atLeast(hlt,2);m.hu15=100-m.ho15;double p0=Math.exp(-hlt),p1g=hlt*Math.exp(-hlt);m.hu10=(int)Math.round(p0*100);m.hPush10=(int)Math.round(p1g*100);m.ho10=Math.max(0,100-m.hu10-m.hPush10);
        if(liveMode){double rem=clamp((95.0-Math.max(0,m.min))/95.0,0,1),press=0;if(m.liveXgH+m.liveXgA>0)press+=.30*(m.liveXgH-m.liveXgA);if(m.liveSotH+m.liveSotA>0)press+=.05*(m.liveSotH-m.liveSotA);if(m.liveShotsH+m.liveShotsA>0)press+=.015*(m.liveShotsH-m.liveShotsA);press=clamp(press,-.55,.55);double rh=clamp(m.lambdaH*rem*(1+press),.01,2.8),ra=clamp(m.lambdaA*rem*(1-press),.01,2.8);int hg=Math.max(0,m.hg),ag=Math.max(0,m.ag);int[]lp=outcomeArray(hg,ag,rh,ra);m.p1=lp[0];m.px=lp[1];m.p2=lp[2];m.next1=atLeast(rh+ra,1);m.next2=atLeast(rh+ra,2);m.next3=atLeast(rh+ra,3);double no=Math.exp(-(rh+ra)),any=1-no;m.noMore=(int)Math.round(no*100);m.nextHome=(int)Math.round(any*(rh/(rh+ra))*100);m.nextAway=Math.max(0,100-m.noMore-m.nextHome);}
    }
    private double addC(Match m,String n,boolean ok,double w,double lh,double la,String d){if(!ok){m.criteria.add(new Criterion(n,false,w,-1,-1,-1,0,0,"нет данных"));return w;}int[]p=outcomeArray(0,0,lh,la);m.criteria.add(new Criterion(n,true,w,p[0],p[1],p[2],lh,la,d));return w;}
    private double addDiffC(Match m,String n,boolean ok,double w,double hd,double ad,String d){double lh=clamp(1.30*(1+.06*hd-.03*ad),.35,2.8),la=clamp(1.10*(1+.06*ad-.03*hd),.30,2.6);return addC(m,n,ok,w,lh,la,d);}
    private int[] outcomeArray(int bh,int ba,double lh,double la){double p1=0,px=0,p2=0;for(int h=0;h<10;h++)for(int a=0;a<10;a++){double p=pois(h,lh)*pois(a,la);int fh=bh+h,fa=ba+a;if(fh>fa)p1+=p;else if(fh==fa)px+=p;else p2+=p;}double s=p1+px+p2;if(s<=0)return new int[]{-1,-1,-1};int x=(int)Math.round(p1/s*100),y=(int)Math.round(px/s*100);return new int[]{x,y,100-x-y};}
    private int atLeast(double l,int n){double x=0;for(int i=0;i<n;i++)x+=pois(i,l);return(int)Math.round(clamp(1-x,0,1)*100);}private double pois(int k,double l){double f=1;for(int i=2;i<=k;i++)f*=i;return Math.exp(-l)*Math.pow(l,k)/f;}

    private void render(){LinearLayout root=v();root.setBackgroundColor(BG);root.setPadding(dp(14),dp(10),dp(14),dp(10));TextView title=txt("DENZL",26,TEXT,true);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=txt("BETCITY: линия · SofaScore/FotMob: статистика",12,MUTED,false);sub.setGravity(Gravity.CENTER);root.addView(sub);
        LinearLayout tabs=new LinearLayout(this);tabs.setWeightSum(2);Button lb=tab("ЛИНИЯ",!liveMode),lv=tab("LIVE",liveMode);tabs.addView(lb,new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(lv,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.setMargins(0,dp(8),0,0);root.addView(tabs,tp);lb.setOnClickListener(x->{liveMode=false;stopLive();results.clear();status="Введите команду или лигу";render();});lv.setOnClickListener(x->{liveMode=true;results.clear();status="Введите команду или лигу LIVE";render();startLive();});
        LinearLayout sr=new LinearLayout(this);EditText ed=new EditText(this);ed.setText(query);ed.setHint("Например: КАМАЗ, Интер, Челябинск");ed.setSingleLine(true);ed.setTextColor(TEXT);ed.setHintTextColor(MUTED);ed.setBackground(box(CARD2,12));ed.setPadding(dp(12),0,dp(8),0);Button go=tab("НАЙТИ",true);sr.addView(ed,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(dp(96),dp(48));gp.setMargins(dp(7),0,0,0);sr.addView(go,gp);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(9),0,0);root.addView(sr,sp);go.setOnClickListener(x->search(ed.getText().toString(),liveMode));ed.setOnEditorActionListener((v,a,e)->{search(v.getText().toString(),liveMode);return true;});
        TextView st=txt(status,12,busy.get()?ACCENT:(status.toLowerCase(Locale.ROOT).contains("ошиб")?RED:GREEN),true);st.setGravity(Gravity.CENTER);st.setPadding(0,dp(8),0,dp(4));root.addView(st);if(liveMode)root.addView(txt("LIVE найденного запроса обновляется каждые 30 секунд",10,MUTED,false));ScrollView sc=new ScrollView(this);LinearLayout list=v();for(Match m:results)list.addView(card(m));sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private View card(Match m){LinearLayout c=v();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(box(CARD,15));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(8),0,0);c.setLayoutParams(cp);LinearLayout top=new LinearLayout(this);top.addView(txt(m.league,11,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));top.addView(txt(m.min>0?m.min+"'":time(m.ts),11,m.min>0?GREEN:MUTED,true));c.addView(top);String score=m.hg>=0?"  "+m.hg+":"+m.ag:"";TextView teams=txt(m.home+" — "+m.away+score,17,TEXT,true);teams.setPadding(0,dp(6),0,dp(6));c.addView(teams);c.addView(outcomes(m));if(!m.ready){Button calc=tab(m.loading?"СБОР СТАТИСТИКИ…":"РАССЧИТАТЬ ВЕРОЯТНОСТЬ",false);calc.setEnabled(!m.loading);c.addView(calc,new LinearLayout.LayoutParams(-1,dp(46)));calc.setOnClickListener(x->analyze(m));if(!m.error.isEmpty())c.addView(txt(m.error,11,RED,false));}else{TextView rel=txt("Качество данных: "+m.reliability+"% · "+m.ph.source+" / "+m.pa.source,11,m.reliability>=70?GREEN:AMBER,true);rel.setPadding(0,dp(5),0,dp(5));c.addView(rel);if(liveMode){addSingle(c,"Ещё 1+ гол",m.next1);addSingle(c,"Ещё 2+ гола",m.next2);addSingle(c,"Ещё 3+ гола",m.next3);LinearLayout r=new LinearLayout(this);r.setWeightSum(3);r.addView(prob("След. хозяева",m.nextHome,0,false),new LinearLayout.LayoutParams(0,dp(66),1));r.addView(prob("След. гости",m.nextAway,0,false),new LinearLayout.LayoutParams(0,dp(66),1));r.addView(prob("Голов не будет",m.noMore,0,false),new LinearLayout.LayoutParams(0,dp(66),1));c.addView(r);}else{addTotal(c,"ТОТАЛ 2.5","ТБ 2.5",m.o25,m.o25Odd,"ТМ 2.5",m.u25,m.u25Odd);addTotal(c,"ТОТАЛ 1.5","ТБ 1.5",m.o15,m.o15Odd,"ТМ 1.5",m.u15,m.u15Odd);}addTotal(c,"ОБЕ ЗАБЬЮТ","ДА",m.bttsYes,m.bttsYesOdd,"НЕТ",m.bttsNo,m.bttsNoOdd);TextView ht=txt("1-Й ТАЙМ",12,ACCENT,true);ht.setPadding(0,dp(8),0,dp(3));c.addView(ht);addTotal(c,"Тотал 1-го тайма 0.5","ТБ 0.5",m.ho05,m.ho05Odd,"ТМ 0.5",m.hu05,m.hu05Odd);addTotal(c,"Тотал 1-го тайма 1.0","ТБ 1.0",m.ho10,m.ho10Odd,"ТМ 1.0",m.hu10,m.hu10Odd);TextView push=txt("Возврат при 1 голе: "+m.hPush10+"%",10,MUTED,false);push.setGravity(Gravity.CENTER);c.addView(push);addTotal(c,"Тотал 1-го тайма 1.5","ТБ 1.5",m.ho15,m.ho15Odd,"ТМ 1.5",m.hu15,m.hu15Odd);TextView au=txt("Показать проверку критериев",12,ACCENT,true);au.setGravity(Gravity.CENTER);au.setPadding(0,dp(7),0,0);c.addView(au);au.setOnClickListener(x->toggleAudit(c,au,m));}return c;}
    private View outcomes(Match m){LinearLayout r=new LinearLayout(this);r.setWeightSum(3);r.addView(prob("П1",m.p1,m.p1Odd,false),new LinearLayout.LayoutParams(0,dp(70),1));r.addView(prob("X",m.px,m.xOdd,false),new LinearLayout.LayoutParams(0,dp(70),1));r.addView(prob("П2",m.p2,m.p2Odd,false),new LinearLayout.LayoutParams(0,dp(70),1));return r;}
    private void toggleAudit(LinearLayout c,TextView ctl,Match m){Object tag=ctl.getTag();if(tag instanceof View){c.removeView((View)tag);ctl.setTag(null);return;}LinearLayout b=v();b.setPadding(dp(8),dp(8),dp(8),dp(8));b.setBackground(box(CARD2,10));for(Criterion x:m.criteria){LinearLayout r=new LinearLayout(this);LinearLayout l=v();l.addView(txt(x.name,11,x.available?TEXT:MUTED,true));l.addView(txt(x.detail,9,MUTED,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));r.addView(txt(x.available?(x.p1+" / "+x.px+" / "+x.p2+"% · вес "+fmt(x.w)):"—",10,x.available?GREEN:MUTED,true));b.addView(r);}c.addView(b);ctl.setTag(b);}
    private void addSingle(LinearLayout b,String t,int p){TextView h=txt(t,10,MUTED,true);h.setPadding(0,dp(6),0,dp(2));b.addView(h);b.addView(prob(t,p,0,p>=60),new LinearLayout.LayoutParams(-1,dp(62)));}
    private void addTotal(LinearLayout p,String title,String l,int lp,double lo,String r,int rp,double ro){TextView t=txt(title,10,MUTED,true);t.setPadding(0,dp(7),0,dp(3));p.addView(t);LinearLayout x=new LinearLayout(this);x.setWeightSum(2);x.addView(prob(l,lp,lo,lp>=58&&lp>rp),new LinearLayout.LayoutParams(0,dp(66),1));x.addView(prob(r,rp,ro,rp>=58&&rp>lp),new LinearLayout.LayoutParams(0,dp(66),1));p.addView(x);}
    private View prob(String label,int p,double odd,boolean hi){LinearLayout b=v();b.setGravity(Gravity.CENTER);b.setBackground(box(hi?GREEN:CARD2,10));b.addView(txt(label,10,hi?Color.WHITE:MUTED,true));String s=(p<0?"—":p+"%")+(odd>1?" ("+String.format(Locale.US,"%.2f",odd)+")":"");b.addView(txt(s,15,Color.WHITE,true));return b;}

    private void scanMarkets(Object node,Match m,String inherited){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String market=inherited,n=o.optString("name","");if(!n.isEmpty())market=n;String n2=o.optString("name_m","");if(!n2.isEmpty())market=n2;if(o.has("P1")||o.has("P2")||o.has("X")||o.has("Tb")||o.has("Tm")||o.has("Y")||o.has("N"))applyBlock(o,market,m);JSONObject blocks=o.optJSONObject("blocks");if(blocks!=null){Iterator<String>it=blocks.keys();while(it.hasNext()){Object b=blocks.opt(it.next());if(b instanceof JSONObject)applyBlock((JSONObject)b,market,m);}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)scanMarkets(v,m,market);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)scanMarkets(v,m,inherited);}}}
    private void applyBlock(JSONObject b,String market,Match m){String ml=(market==null?"":market).toLowerCase(Locale.ROOT);boolean first=ml.contains("1-й тайм")||ml.contains("1 тайм")||ml.contains("первый тайм")||ml.contains("1st half")||ml.contains("first half");if(b.has("P1")||b.has("P2")||b.has("X")){if(first){m.hp1Odd=odd(b.opt("P1"));m.hxOdd=odd(b.opt("X"));m.hp2Odd=odd(b.opt("P2"));}else if(m.p1Odd<=0){m.p1Odd=odd(b.opt("P1"));m.xOdd=odd(b.opt("X"));m.p2Odd=odd(b.opt("P2"));}}if(b.has("Tb")||b.has("Tm")){double line=marketLine(b),ov=odd(b.opt("Tb")),un=odd(b.opt("Tm"));if(first){if(close(line,.5)){m.ho05Odd=ov;m.hu05Odd=un;}else if(close(line,1)){m.ho10Odd=ov;m.hu10Odd=un;}else if(close(line,1.5)){m.ho15Odd=ov;m.hu15Odd=un;}}else{if(close(line,1.5)){m.o15Odd=ov;m.u15Odd=un;}else if(close(line,2.5)){m.o25Odd=ov;m.u25Odd=un;}}}if((ml.contains("обе забьют")||ml.contains("both teams"))&&(b.has("Y")||b.has("N"))){m.bttsYesOdd=odd(b.opt("Y"));m.bttsNoOdd=odd(b.opt("N"));}}
    private double marketLine(JSONObject b){double v=num(b.opt("Tot"));if(v<=0)v=lineOutcome(b.opt("Tb"));if(v<=0)v=lineOutcome(b.opt("Tm"));return v;}private double lineOutcome(Object x){if(!(x instanceof JSONObject))return 0;JSONObject o=(JSONObject)x;double v=num(o.opt("lv"));if(v==0)v=num(o.opt("lvt"));if(v==0)v=num(o.opt("lvl"));return Math.abs(v);}private double odd(Object x){return x instanceof JSONObject?num(((JSONObject)x).opt("kf")):num(x);}private boolean close(double a,double b){return Math.abs(a-b)<.06;}
    private void scanStats(Object node,Match m){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;if(o.has("name_ext")&&o.has("value_ext")){String n=o.optString("name_ext","").toLowerCase(Locale.ROOT);double[]p=parsePair(o.opt("value_ext"));if(p!=null){if(n.contains("expected")||n.equals("xg")||n.contains("ожидаем")){m.liveXgH=p[0];m.liveXgA=p[1];}else if(n.contains("в створ")||n.contains("on target")){m.liveSotH=p[0];m.liveSotA=p[1];}else if(n.contains("удар")||n.contains("shots")){m.liveShotsH=p[0];m.liveShotsA=p[1];}}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)scanStats(v,m);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)scanStats(v,m);}}}

    private JSONObject getJson(String u,String ref)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(12000);c.setRequestProperty("Accept","application/json, text/plain, */*");c.setRequestProperty("Accept-Language","ru-RU,ru;q=0.9,en;q=0.7");c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36");if(ref!=null)c.setRequestProperty("Referer",ref);int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String body=read(is);c.disconnect();if(code<200||code>=300)throw new Exception("HTTP "+code);if(body.trim().isEmpty())throw new Exception("пустой ответ");return new JSONObject(body);}private String read(InputStream is)throws Exception{if(is==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(is));StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s);r.close();return b.toString();}
    private String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}private boolean truth(Object o){String s=String.valueOf(o);return"1".equals(s)||"true".equalsIgnoreCase(s)||"yes".equalsIgnoreCase(s);}private int findMinute(JSONObject e){String[]k={"minute","min","time_ev","timer","time_game","current_minute"};for(String q:k)if(e.has(q)){int x=parseInt(String.valueOf(e.opt(q)));if(x>0&&x<130)return x;}return 0;}private void parseScore(String s,Match m,boolean half){int[]x=parsePairScore(s);if(x==null)return;if(half){m.h1g=x[0];m.a1g=x[1];}else{m.hg=x[0];m.ag=x[1];}}private int[] parsePairScore(String s){if(s==null)return null;java.util.regex.Matcher q=java.util.regex.Pattern.compile("(\\d+)\\s*[:\\-]\\s*(\\d+)").matcher(s);if(!q.find())return null;return new int[]{Integer.parseInt(q.group(1)),Integer.parseInt(q.group(2))};}private double[] parsePair(Object v){String s=String.valueOf(v);java.util.regex.Matcher m=java.util.regex.Pattern.compile("(-?\\d+(?:[.,]\\d+)?)").matcher(s);double[]x=new double[2];int i=0;while(m.find()&&i<2)x[i++]=num(m.group(1));return i==2?x:null;}
    private long parseDate(Object o){if(o instanceof Number){long v=((Number)o).longValue();return v>100000000000L?v/1000:v;}String s=String.valueOf(o);if(s.matches("\\d{10,13}"))try{long v=Long.parseLong(s);return v>100000000000L?v/1000:v;}catch(Exception ignored){}String[]f={"yyyy-MM-dd HH:mm:ss","yyyy-MM-dd HH:mm","dd.MM.yyyy HH:mm"};for(String p:f)try{Date d=new SimpleDateFormat(p,Locale.US).parse(s);if(d!=null)return d.getTime()/1000;}catch(Exception ignored){}return 0;}private String cleanLeague(String s){if(s==null||s.trim().isEmpty())return"Прочие соревнования";return s.trim().replaceFirst("(?i)^soccer\\.\\s*","").replaceFirst("(?i)^football\\.\\s*","");}private String country(String s){if(s==null)return"Прочее";String[]p=s.split("\\.");return p.length>1?p[0].trim():"Прочее";}private int similarity(String a,String b){String x=norm(a),y=norm(b);if(x.equals(y))return100;if(x.contains(y)||y.contains(x))return80;int sc=0;for(String t:x.split(" "))if(t.length()>2&&y.contains(t))sc+=20;return sc;}private String norm(String s){if(s==null)return"";return s.toLowerCase(Locale.ROOT).replace('ё','е').replaceAll("[^\\p{L}\\p{N}]+"," ").trim();}private String key(String s){return norm(s).replace(" ","");}private double num(Object o){if(o==null)return 0;try{return Double.parseDouble(String.valueOf(o).replace("%","").replace(',','.').replaceAll("[^0-9.\\-]",""));}catch(Exception e){return 0;}}private int parseInt(String s){try{java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d{1,3})").matcher(s);return m.find()?Integer.parseInt(m.group(1)):0;}catch(Exception e){return 0;}}private String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}private double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));}private String fmt(double v){return String.format(Locale.US,"%.1f",v);}private String time(long ts){return ts<=0?"—":new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(ts*1000));}
    private LinearLayout v(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private Button tab(String s,boolean on){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(box(on?ACCENT:CARD2,11));return b;}private TextView txt(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}

    static class Hist{int eventId,gf,ga,h1gf=-1,h1ga=-1;boolean teamHome;}
    static class Profile{String source="";long loadedAt;int n,w,d,l,homeN,awayN,h1N;double gf,ga,homeGF,homeGA,awayGF,awayGA,h1GF,h1GA,xgF,xgA,sotF,sotA,shF,shA,posF,posA,corF,corA,cardF,cardA;int xgN,sotN,shN,posN,corN,cardN,statN;void addResult(Hist h){if(n>=20)return;n++;gf+=h.gf;ga+=h.ga;if(h.gf>h.ga)w++;else if(h.gf==h.ga)d++;else l++;if(h.teamHome){homeN++;homeGF+=h.gf;homeGA+=h.ga;}else{awayN++;awayGF+=h.gf;awayGA+=h.ga;}if(h.h1gf>=0&&h.h1ga>=0){h1N++;h1GF+=h.h1gf;h1GA+=h.h1ga;}}double gf(){return n>0?gf/n:1.2;}double ga(){return n>0?ga/n:1.2;}double form(){return n>0?(3.0*w+d)/(3.0*n):.5;}double homeGF(){return homeN>0?homeGF/homeN:gf();}double homeGA(){return homeN>0?homeGA/homeN:ga();}double awayGF(){return awayN>0?awayGF/awayN:gf();}double awayGA(){return awayN>0?awayGA/awayN:ga();}double h1gf(){return h1N>0?h1GF/h1N:gf()*.46;}double h1ga(){return h1N>0?h1GA/h1N:ga()*.46;}double xgF(){return xgN>0?xgF/xgN:0;}double xgA(){return xgN>0?xgA/xgN:0;}double sotF(){return sotN>0?sotF/sotN:0;}double sotA(){return sotN>0?sotA/sotN:0;}double shF(){return shN>0?shF/shN:0;}double shA(){return shN>0?shA/shN:0;}double posF(){return posN>0?posF/posN:0;}double corF(){return corN>0?corF/corN:0;}double corA(){return corN>0?corA/corN:0;}double cardF(){return cardN>0?cardF/cardN:0;}double cardA(){return cardN>0?cardA/cardN:0;}}
    static class Criterion{String name,detail;boolean available;double w,lh,la;int p1,px,p2;Criterion(String n,boolean a,double w,int p1,int px,int p2,double lh,double la,String d){name=n;available=a;this.w=w;this.p1=p1;this.px=px;this.p2=p2;this.lh=lh;this.la=la;detail=d;}}
    static class Match{String id="",country="",league="",home="",away="",error="";long ts;int min=0,hg=-1,ag=-1,h1g=-1,a1g=-1,p1=-1,px=-1,p2=-1,reliability=0,o15=-1,u15=-1,o25=-1,u25=-1,bttsYes=-1,bttsNo=-1,h1p1=-1,h1px=-1,h1p2=-1,ho05=-1,hu05=-1,ho10=-1,hu10=-1,hPush10=-1,ho15=-1,hu15=-1,next1=-1,next2=-1,next3=-1,nextHome=-1,nextAway=-1,noMore=-1;double p1Odd,xOdd,p2Odd,o15Odd,u15Odd,o25Odd,u25Odd,bttsYesOdd,bttsNoOdd,hp1Odd,hxOdd,hp2Odd,ho05Odd,hu05Odd,ho10Odd,hu10Odd,ho15Odd,hu15Odd,liveXgH,liveXgA,liveSotH,liveSotA,liveShotsH,liveShotsA,lambdaH,lambdaA;boolean loading=false,ready=false;Profile ph,pa;final List<Criterion>criteria=new ArrayList<>();}
}
