package ru.matchstats.app;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

public class MainActivity extends Activity {
    private static final String SOFA="https://api.sofascore.com/api/v1";
    private static final String FOT="https://www.fotmob.com/api/data";
    private static final String BC_PRE="https://ad.betcity.ru/d/off/events?id_sp=1&ch_id=0&gr_id=0&add=main,ext,name_sp,name_ch&rev=2&ver=69&csn=ooca9s";
    private static final String[] BC_LIVE={
            "https://ad.betcity.ru/d/on_air/bets?id_sp=1&rev=8&add=dep_event,name_sp,name_ch&template=1&ver=69&csn=ooca9s",
            "https://ad.betcity.ru/d/on_air/bets?id_sp=1&rev=2&add=name_sp,name_ch&template=1&ver=69&csn=ooca9s"};
    private static final long LIVE_REFRESH_MS=120000L;
    private static final double MIN_ODD=1.45;

    private static final int BG=Color.rgb(8,14,20),CARD=Color.rgb(18,29,39),CARD2=Color.rgb(25,39,52),TEXT=Color.rgb(243,247,250),MUTED=Color.rgb(145,160,174),GREEN=Color.rgb(40,185,105),ACCENT=Color.rgb(47,140,255),RED=Color.rgb(232,78,84),AMBER=Color.rgb(240,171,55);
    private final ExecutorService io=Executors.newFixedThreadPool(6);
    private final AtomicBoolean busy=new AtomicBoolean(false);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final List<Match> matches=new ArrayList<>();
    private final Map<String,Profile> profileCache=new LinkedHashMap<>();
    private final Map<String,Match> selectedLive=new HashMap<>();
    private final Map<String,List<Match>> searchCache=new HashMap<>();
    private boolean live=false;
    private String query="",status="Введите команду, лигу или страну";
    private JSONObject oddsPreCache,oddsLiveCache; private long oddsPreAt=0,oddsLiveAt=0;

    @Override public void onCreate(Bundle b){super.onCreate(b);render();}
    @Override public void onDestroy(){handler.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}

    private final Runnable liveTick=new Runnable(){@Override public void run(){if(live){loadLive(false);handler.postDelayed(this,LIVE_REFRESH_MS);}}};
    private void startLive(){handler.removeCallbacks(liveTick);loadLive(true);handler.postDelayed(liveTick,LIVE_REFRESH_MS);} private void stopLive(){handler.removeCallbacks(liveTick);}

    private void searchLine(String q){
        q=q==null?"":q.trim();if(q.length()<2){status="Введите не менее 2 символов";render();return;}query=q;String key=norm(q);
        List<Match> c=searchCache.get(key);if(c!=null){matches.clear();matches.addAll(cloneList(c));status="Найдено: "+matches.size()+" · из кэша";render();return;}
        if(!busy.compareAndSet(false,true))return;status="Ищу матчи…";render();final String fq=q;
        io.execute(()->{List<Match> out=new ArrayList<>();String err="";try{
            JSONObject sr=getJson(SOFA+"/search/all?q="+enc(fq),"https://www.sofascore.com/");int team=findTeam(sr,fq);
            if(team>0)for(int p=0;p<2&&out.size()<25;p++){JSONObject r=getJson(SOFA+"/team/"+team+"/events/next/"+p,"https://www.sofascore.com/");collectEvents(r,out,false,"",false);}
            if(out.isEmpty()){long now=System.currentTimeMillis();for(int d=0;d<7;d++){String ds=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date(now+d*86400000L));try{JSONObject r=getJson(SOFA+"/sport/football/scheduled-events/"+ds,"https://www.sofascore.com/");collectEvents(r,out,false,fq,true);}catch(Exception ignored){}}}
            dedupe(out);sortMatches(out);
        }catch(Exception e){err=msg(e);}final String er=err;runOnUiThread(()->{matches.clear();matches.addAll(out);searchCache.put(key,cloneList(out));status=out.isEmpty()?(!er.isEmpty()?er:"Матчи не найдены"):("Найдено: "+out.size());busy.set(false);render();});});
    }

    private void loadLive(boolean first){if(!live||!busy.compareAndSet(false,true))return;if(first){status="Загружаю матчи LIVE…";render();}
        io.execute(()->{List<Match> out=new ArrayList<>();String err="";try{JSONObject r=getJson(SOFA+"/sport/football/events/live","https://www.sofascore.com/");collectEvents(r,out,true,"",false);dedupe(out);sortMatches(out);}catch(Exception e){err=msg(e);}final String er=err;runOnUiThread(()->{matches.clear();for(Match n:out){Match old=selectedLive.get(n.id);if(old!=null){n.ph=old.ph;n.pa=old.pa;n.ready=old.ready;n.criteria.addAll(old.criteria);n.lambdaH=old.lambdaH;n.lambdaA=old.lambdaA;n.reliability=old.reliability;}matches.add(n);}status=er.isEmpty()?"LIVE: "+matches.size()+" матчей · обновление 2 мин":er;busy.set(false);render();for(Match m:new ArrayList<>(matches))if(m.ready)refreshLive(m);});});}

    private void collectEvents(Object node,List<Match> out,boolean isLive,String q,boolean filter){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;JSONArray a=o.optJSONArray("events");if(a!=null){for(int i=0;i<a.length();i++){Match m=parseEvent(a.optJSONObject(i),isLive);if(m!=null&&(!filter||matchesQuery(m,q)))out.add(m);}return;}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)collectEvents(v,out,isLive,q,filter);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)collectEvents(v,out,isLive,q,filter);}}}

    private Match parseEvent(JSONObject e,boolean isLive){if(e==null)return null;JSONObject sp=e.optJSONObject("sport");if(sp!=null&&!"football".equalsIgnoreCase(sp.optString("slug","football")))return null;JSONObject ht=e.optJSONObject("homeTeam"),at=e.optJSONObject("awayTeam");if(ht==null||at==null)return null;JSONObject t=e.optJSONObject("tournament"),ut=t==null?null:t.optJSONObject("uniqueTournament"),cat=t==null?null:t.optJSONObject("category");String rh=ht.optString("name","").trim(),ra=at.optString("name","").trim(),rl=ut!=null?ut.optString("name",""):t==null?"":t.optString("name","");String rc=cat==null?"Прочее":cat.optString("name","Прочее");if(rh.isEmpty()||ra.isEmpty()||excluded(rc+" "+rl+" "+rh+" "+ra))return null;Match m=new Match();m.id=String.valueOf(e.optLong("id",0));m.rawHome=rh;m.rawAway=ra;m.home=ru(rh);m.away=ru(ra);m.league=ruLeague(rl);m.country=ruCountry(rc);m.ts=e.optLong("startTimestamp",0);m.live=isLive;JSONObject hs=e.optJSONObject("homeScore"),as=e.optJSONObject("awayScore");if(hs!=null&&as!=null){m.hg=scoreVal(hs);m.ag=scoreVal(as);}m.min=findMinute(e);return m;}

    private void analyze(Match m){if(m.loading)return;m.loading=true;m.error="";status="Собираю статистику выбранного матча…";render();io.execute(()->{try{m.ph=getProfile(m.rawHome);m.pa=getProfile(m.rawAway);if(m.live)loadLiveStats(m);loadOdds(m);calculate(m);if(m.live)selectedLive.put(m.id,m);}catch(Exception e){m.error=msg(e);}m.loading=false;runOnUiThread(()->{status=m.error.isEmpty()?"Расчёт выполнен · вероятность не зависит от коэффициента":"Ошибка: "+m.error;render();});});}
    private void refreshLive(Match m){if(m.loading||m.ph==null||m.pa==null)return;m.loading=true;io.execute(()->{try{loadLiveStats(m);loadOdds(m);calculate(m);selectedLive.put(m.id,m);}catch(Exception e){m.error=msg(e);}m.loading=false;runOnUiThread(this::render);});}

    private Profile getProfile(String name)throws Exception{String k=norm(name);Profile c=profileCache.get(k);if(c!=null&&System.currentTimeMillis()-c.loadedAt<3600000)return c;Profile p=null;Exception last=null;try{p=sofaProfile(name);}catch(Exception e){last=e;}if(p==null||p.n<5)try{Profile f=fotProfile(name);if(f!=null&&(p==null||f.n>p.n))p=f;}catch(Exception e){last=e;}if(p==null||p.n<3)throw last!=null?last:new Exception("Недостаточно истории команды");p.loadedAt=System.currentTimeMillis();profileCache.put(k,p);return p;}
    private Profile sofaProfile(String name)throws Exception{JSONObject sr=getJson(SOFA+"/search/all?q="+enc(name),"https://www.sofascore.com/");int id=findTeam(sr,name);if(id<=0)throw new Exception("SofaScore: команда не найдена");Profile p=new Profile();p.source="SofaScore";List<Hist> hist=new ArrayList<>();for(int page=0;page<2&&hist.size()<20;page++){JSONObject r=getJson(SOFA+"/team/"+id+"/events/last/"+page,"https://www.sofascore.com/");JSONArray a=r.optJSONArray("events");if(a==null)break;for(int i=0;i<a.length()&&hist.size()<20;i++){Hist h=parseHist(a.optJSONObject(i),id);if(h!=null)hist.add(h);}}for(Hist h:hist){p.add(h);if(p.statN<10&&h.id>0)try{JSONObject s=getJson(SOFA+"/event/"+h.id+"/statistics","https://www.sofascore.com/");addStats(s,p,h.home);}catch(Exception ignored){}}return p;}
    private Profile fotProfile(String name)throws Exception{JSONObject sr=getJson(FOT+"/search/suggest?hits=20&lang=en&term="+enc(name),"https://www.fotmob.com/");int id=findFot(sr,name);if(id<=0)throw new Exception("FotMob: команда не найдена");JSONObject tr=getJson(FOT+"/teams?id="+id,"https://www.fotmob.com/");Profile p=new Profile();p.source="FotMob";walkFot(tr,id,p);return p;}

    private Hist parseHist(JSONObject e,int id){if(e==null)return null;JSONObject h=e.optJSONObject("homeTeam"),a=e.optJSONObject("awayTeam"),hs=e.optJSONObject("homeScore"),as=e.optJSONObject("awayScore");if(h==null||a==null||hs==null||as==null)return null;boolean home=h.optInt("id")==id;if(!home&&a.optInt("id")!=id)return null;int hg=scoreVal(hs),ag=scoreVal(as);if(hg<0||ag<0)return null;Hist x=new Hist();x.id=e.optInt("id",0);x.home=home;x.gf=home?hg:ag;x.ga=home?ag:hg;x.h1gf=home?hs.optInt("period1",-1):as.optInt("period1",-1);x.h1ga=home?as.optInt("period1",-1):hs.optInt("period1",-1);return x;}
    private void addStats(Object node,Profile p,boolean home){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;if(o.has("name")&&o.has("home")&&o.has("away")){String n=o.optString("name","").toLowerCase(Locale.ROOT);double hv=num(o.opt("home")),av=num(o.opt("away")),f=home?hv:av,a=home?av:hv;if(n.contains("expected goals")||n.equals("xg")){p.xgF+=f;p.xgA+=a;p.xgN++;}else if(n.contains("shots on target")){p.sotF+=f;p.sotA+=a;p.sotN++;}else if(n.contains("total shots")){p.shF+=f;p.shA+=a;p.shN++;}else if(n.contains("possession")){p.posF+=f;p.posA+=a;p.posN++;}else if(n.contains("corner")){p.corF+=f;p.corA+=a;p.corN++;}else if(n.contains("yellow card")){p.cardF+=f;p.cardA+=a;p.cardN++;}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)addStats(v,p,home);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)addStats(v,p,home);}}p.statN=Math.max(p.statN,Math.max(p.xgN,Math.max(p.sotN,p.shN)));}

    private void loadLiveStats(Match m){try{JSONObject s=getJson(SOFA+"/event/"+m.id+"/statistics","https://www.sofascore.com/");scanLive(s,m);}catch(Exception ignored){}}
    private void scanLive(Object node,Match m){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;if(o.has("name")&&o.has("home")&&o.has("away")){String n=o.optString("name","").toLowerCase(Locale.ROOT);double h=num(o.opt("home")),a=num(o.opt("away"));if(n.contains("expected goals")){m.liveXgH=h;m.liveXgA=a;}else if(n.contains("shots on target")){m.liveSotH=h;m.liveSotA=a;}else if(n.contains("total shots")){m.liveShotsH=h;m.liveShotsA=a;}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)scanLive(v,m);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)scanLive(v,m);}}}

    private void loadOdds(Match m)throws Exception{JSONObject root=loadOddsRoot(m.live);OddCandidate best=new OddCandidate();walkOdds(root,m,best,"",-1,"",false);if(best.score>0){copyOdds(best.m,m);m.oddSource="BETCITY";}}
    private JSONObject loadOddsRoot(boolean lv)throws Exception{long now=System.currentTimeMillis();if(lv&&oddsLiveCache!=null&&now-oddsLiveAt<30000)return oddsLiveCache;if(!lv&&oddsPreCache!=null&&now-oddsPreAt<120000)return oddsPreCache;if(lv){Exception last=null;for(String u:BC_LIVE)try{JSONObject x=getJson(u,"https://betcity.ru/ru/live/football");oddsLiveCache=x;oddsLiveAt=now;return x;}catch(Exception e){last=e;}throw last!=null?last:new Exception("коэффициенты LIVE недоступны");}JSONObject x=getJson(BC_PRE,"https://betcity.ru/ru/line/football");oddsPreCache=x;oddsPreAt=now;return x;}
    private void walkOdds(Object node,Match target,OddCandidate best,String league,int sport,String sportName,boolean inheritedLive){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String nl=o.has("name_ch")?o.optString("name_ch",league):league,ns=o.has("name_sp")?o.optString("name_sp",sportName):sportName;int ni=o.has("id_sp")?o.optInt("id_sp",sport):sport;boolean lv=inheritedLive||truth(o.opt("is_live"));if(o.has("id_ev")&&o.has("name_ht")&&o.has("name_at")&&(ni==1||ns.toLowerCase(Locale.ROOT).contains("футбол")||ns.toLowerCase(Locale.ROOT).contains("football"))){String h=o.optString("name_ht",""),a=o.optString("name_at","");int sc=similarity(target.rawHome,h)+similarity(target.rawAway,a);if(sc>best.score){Match x=new Match();scanMarkets(o,x,"");best.score=sc;best.m=x;}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkOdds(v,target,best,nl,ni,ns,lv);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkOdds(v,target,best,league,sport,sportName,inheritedLive);}}}
    private void scanMarkets(Object node,Match m,String inherited){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String mk=inherited;if(!o.optString("name","").isEmpty())mk=o.optString("name","");if(!o.optString("name_m","").isEmpty())mk=o.optString("name_m","");applyMarket(o,m,mk);JSONObject b=o.optJSONObject("blocks");if(b!=null){Iterator<String>it=b.keys();while(it.hasNext()){Object v=b.opt(it.next());if(v instanceof JSONObject)applyMarket((JSONObject)v,m,mk);}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)scanMarkets(v,m,mk);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)scanMarkets(v,m,inherited);}}}
    private void applyMarket(JSONObject b,Match m,String market){String ml=(market==null?"":market).toLowerCase(Locale.ROOT);boolean first=ml.contains("1-й тайм")||ml.contains("1 тайм")||ml.contains("first half")||ml.contains("1st half");if(b.has("P1")||b.has("P2")||b.has("X")){if(first){m.hP1Odd=odd(b.opt("P1"));m.hXOdd=odd(b.opt("X"));m.hP2Odd=odd(b.opt("P2"));}else if(m.p1Odd<=0){m.p1Odd=odd(b.opt("P1"));m.xOdd=odd(b.opt("X"));m.p2Odd=odd(b.opt("P2"));}}if(b.has("Tb")||b.has("Tm")){double line=marketLine(b),ov=odd(b.opt("Tb")),un=odd(b.opt("Tm"));if(first){if(close(line,.5)){m.hO05Odd=ov;m.hU05Odd=un;}else if(close(line,1)){m.hO10Odd=ov;m.hU10Odd=un;}else if(close(line,1.5)){m.hO15Odd=ov;m.hU15Odd=un;}}else{if(close(line,1.5)){m.o15Odd=ov;m.u15Odd=un;}else if(close(line,2.5)){m.o25Odd=ov;m.u25Odd=un;}else if(close(line,3.5)){m.o35Odd=ov;m.u35Odd=un;}}}if((ml.contains("обе забьют")||ml.contains("both teams"))&&(b.has("Y")||b.has("N"))){m.bttsYesOdd=odd(b.opt("Y"));m.bttsNoOdd=odd(b.opt("N"));}if((ml.contains("обе забьют")||ml.contains("both teams"))&&(ml.contains("2.5")||ml.contains("2,5"))){double y=odd(b.opt("Y"));if(y<=0)y=odd(b.opt("P1"));if(y>0)m.bttsO25Odd=y;}}
    private double marketLine(JSONObject b){double v=num(b.opt("Tot"));if(v<=0)v=lineOutcome(b.opt("Tb"));if(v<=0)v=lineOutcome(b.opt("Tm"));return Math.abs(v);}private double lineOutcome(Object x){if(!(x instanceof JSONObject))return 0;JSONObject o=(JSONObject)x;double v=num(o.opt("lv"));if(v==0)v=num(o.opt("lvt"));if(v==0)v=num(o.opt("lvl"));return Math.abs(v);}private double odd(Object x){return x instanceof JSONObject?num(((JSONObject)x).opt("kf")):num(x);}private boolean close(double a,double b){return Math.abs(a-b)<.06;}

    private void calculate(Match m){Profile h=m.ph,a=m.pa;m.criteria.clear();double tw=0,uw=0,lh=0,la=0;
        tw+=crit(m,"Форма последних матчей",h.n>=5&&a.n>=5,1.2,1.15*(.72+h.form()),1.05*(.72+a.form()),h.n+" / "+a.n+" матчей");
        tw+=crit(m,"Голы: атака / оборона",h.n>=5&&a.n>=5,2.0,clamp((h.gf()+a.ga())/2*1.05,.2,3.4),clamp((a.gf()+h.ga())/2*.98,.2,3.2),String.format(Locale.US,"GF/GA %.2f/%.2f · %.2f/%.2f",h.gf(),h.ga(),a.gf(),a.ga()));
        tw+=crit(m,"Дом / выезд",h.homeN>=3&&a.awayN>=3,1.4,clamp((h.homeGF()+a.awayGA())/2,.2,3.4),clamp((a.awayGF()+h.homeGA())/2,.2,3.2),h.homeN+" дом · "+a.awayN+" выезд");
        tw+=crit(m,"xG / xGA",h.xgN>=3&&a.xgN>=3,2.2,clamp((h.xgF()+a.xgA())/2,.2,3.5),clamp((a.xgF()+h.xgA())/2,.2,3.3),h.xgN+" / "+a.xgN+" матчей");
        tw+=diff(m,"Удары в створ",h.sotN>=3&&a.sotN>=3,1.5,h.sotF()-h.sotA(),a.sotF()-a.sotA(),"ср. "+f1(h.sotF())+" / "+f1(a.sotF()));
        tw+=diff(m,"Удары",h.shN>=3&&a.shN>=3,1.0,h.shF()-h.shA(),a.shF()-a.shA(),"ср. "+f1(h.shF())+" / "+f1(a.shF()));
        tw+=diff(m,"Угловые",h.corN>=3&&a.corN>=3,.6,h.corF()-h.corA(),a.corF()-a.corA(),"ср. "+f1(h.corF())+" / "+f1(a.corF()));
        tw+=diff(m,"Владение",h.posN>=3&&a.posN>=3,.4,(h.posF()-50)/10,(a.posF()-50)/10,"ср. "+f1(h.posF())+"% / "+f1(a.posF())+"%");
        tw+=diff(m,"Карточки",h.cardN>=3&&a.cardN>=3,.3,-(h.cardF()-h.cardA()),-(a.cardF()-a.cardA()),"ср. "+f1(h.cardF())+" / "+f1(a.cardF()));
        for(Criterion c:m.criteria)if(c.ok){uw+=c.w;lh+=c.lh*c.w;la+=c.la*c.w;}double cov=tw>0?uw/tw:0,sample=Math.min(1,Math.min(h.n,a.n)/10.0);m.reliability=(int)Math.round(100*(.72*cov+.28*sample));if(uw<=0||m.reliability<40){m.ready=false;return;}m.lambdaH=lh/uw;m.lambdaA=la/uw;
        double rh=m.lambdaH,ra=m.lambdaA;if(m.live){double rem=clamp((96.0-Math.max(0,m.min))/96.0,0,1),press=0;if(m.liveXgH+m.liveXgA>0)press+=.28*(m.liveXgH-m.liveXgA);if(m.liveSotH+m.liveSotA>0)press+=.045*(m.liveSotH-m.liveSotA);if(m.liveShotsH+m.liveShotsA>0)press+=.012*(m.liveShotsH-m.liveShotsA);press=clamp(press,-.55,.55);rh=clamp(m.lambdaH*rem*(1+press),.01,3);ra=clamp(m.lambdaA*rem*(1-press),.01,3);}
        int baseH=m.live?Math.max(0,m.hg):0,baseA=m.live?Math.max(0,m.ag):0;int[] o=outcome(baseH,baseA,rh,ra);m.p1=o[0];m.px=o[1];m.p2=o[2];double total=rh+ra;m.o15=atLeast(total,2);m.o25=atLeast(total,3);m.o35=atLeast(total,4);m.u15=100-m.o15;m.u25=100-m.o25;m.u35=100-m.o35;m.bttsYes=btts(baseH,baseA,rh,ra);m.bttsNo=100-m.bttsYes;m.bttsO25=bttsOver25(baseH,baseA,rh,ra);double h1h=h.h1N>=4?clamp((h.h1gf()+a.h1ga())/2,.1,1.7):m.lambdaH*.46,h1a=a.h1N>=4?clamp((a.h1gf()+h.h1ga())/2,.1,1.5):m.lambdaA*.46;double ht=h1h+h1a;m.hO05=atLeast(ht,1);m.hO10=asianOverOne(ht);m.hPush10=(int)Math.round(pois(1,ht)*100);m.hO15=atLeast(ht,2);m.hP1=outcome(0,0,h1h,h1a)[0];m.hX=outcome(0,0,h1h,h1a)[1];m.hP2=100-m.hP1-m.hX;m.ready=true;}
    private double crit(Match m,String n,boolean ok,double w,double lh,double la,String d){m.criteria.add(new Criterion(n,ok,w,lh,la,ok?d:"нет данных"));return w;}private double diff(Match m,String n,boolean ok,double w,double hd,double ad,String d){return crit(m,n,ok,w,clamp(1.28*(1+.06*hd-.03*ad),.3,2.9),clamp(1.08*(1+.06*ad-.03*hd),.3,2.7),d);} 
    private int[] outcome(int bh,int ba,double lh,double la){double p1=0,px=0,p2=0;for(int h=0;h<10;h++)for(int a=0;a<10;a++){double p=pois(h,lh)*pois(a,la);int H=bh+h,A=ba+a;if(H>A)p1+=p;else if(H==A)px+=p;else p2+=p;}double s=p1+px+p2;int x=(int)Math.round(p1/s*100),y=(int)Math.round(px/s*100);return new int[]{x,y,100-x-y};}
    private int atLeast(double l,int n){double x=0;for(int i=0;i<n;i++)x+=pois(i,l);return(int)Math.round((1-x)*100);}private int asianOverOne(double l){return(int)Math.round((1-pois(0,l)-pois(1,l))*100);}private int btts(int bh,int ba,double lh,double la){double p=0;for(int h=0;h<9;h++)for(int a=0;a<9;a++)if(bh+h>0&&ba+a>0)p+=pois(h,lh)*pois(a,la);return(int)Math.round(p*100);}private int bttsOver25(int bh,int ba,double lh,double la){double p=0;for(int h=0;h<9;h++)for(int a=0;a<9;a++)if(bh+h>0&&ba+a>0&&bh+ba+h+a>=3)p+=pois(h,lh)*pois(a,la);return(int)Math.round(p*100);}private double pois(int k,double l){double f=1;for(int i=2;i<=k;i++)f*=i;return Math.exp(-l)*Math.pow(l,k)/f;}

    private void render(){LinearLayout root=v();root.setBackgroundColor(BG);root.setPadding(dp(14),dp(8),dp(14),dp(8));TextView title=txt("DENZL",27,TEXT,true);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=txt("Статистика · Модель · Букмекеры · независимые вероятности",11,MUTED,false);sub.setGravity(Gravity.CENTER);root.addView(sub);
        LinearLayout tabs=new LinearLayout(this);tabs.setWeightSum(2);Button l=tab("ЛИНИЯ",!live),lv=tab("LIVE"+(live?" ●":""),live);tabs.addView(l,new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(lv,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.setMargins(0,dp(8),0,0);root.addView(tabs,tp);l.setOnClickListener(x->{live=false;stopLive();matches.clear();status="Введите команду, лигу или страну";render();});lv.setOnClickListener(x->{live=true;matches.clear();query="";startLive();render();});
        if(!live){LinearLayout sr=new LinearLayout(this);EditText ed=new EditText(this);ed.setText(query);ed.setHint("Команда, лига или страна");ed.setSingleLine(true);ed.setTextColor(TEXT);ed.setHintTextColor(MUTED);ed.setBackground(box(CARD2,12));ed.setPadding(dp(12),0,dp(8),0);Button go=tab("НАЙТИ",true);sr.addView(ed,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(dp(96),dp(48));gp.setMargins(dp(7),0,0,0);sr.addView(go,gp);root.addView(sr,new LinearLayout.LayoutParams(-1,dp(56)));go.setOnClickListener(x->searchLine(ed.getText().toString()));ed.setOnEditorActionListener((v,a,e)->{searchLine(v.getText().toString());return true;});}
        TextView st=txt(status,11,busy.get()?ACCENT:(status.toLowerCase(Locale.ROOT).contains("ошиб")?RED:GREEN),true);st.setGravity(Gravity.CENTER);st.setPadding(0,dp(5),0,dp(3));root.addView(st);if(live)root.addView(txt("Счёт, минута, LIVE-коэффициенты и расчёт обновляются каждые 2 минуты",10,MUTED,false));
        ScrollView sc=new ScrollView(this);LinearLayout list=v();String group="";for(Match m:matches){String g=m.country+" · "+m.league;if(live&&!g.equals(group)){TextView gh=txt(g,13,ACCENT,true);gh.setPadding(0,dp(10),0,dp(2));list.addView(gh);group=g;}list.addView(card(m));}sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private View card(Match m){LinearLayout c=v();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(box(CARD,15));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(8),0,0);c.setLayoutParams(cp);LinearLayout top=new LinearLayout(this);top.addView(txt(m.country+" · "+m.league,10,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));top.addView(txt(m.live?(m.min>0?m.min+"'":"LIVE"):dateTime(m.ts),10,m.live?GREEN:MUTED,true));c.addView(top);String score=m.live&&m.hg>=0?"   "+m.hg+":"+m.ag:"";TextView t=txt(m.home+" — "+m.away+score,17,TEXT,true);t.setPadding(0,dp(6),0,dp(7));c.addView(t);
        if(!m.ready){Button b=tab(m.loading?"СБОР ДАННЫХ…":"ОТКРЫТЬ И РАССЧИТАТЬ",false);b.setEnabled(!m.loading);c.addView(b,new LinearLayout.LayoutParams(-1,dp(46)));b.setOnClickListener(x->analyze(m));if(!m.error.isEmpty())c.addView(txt(m.error,10,RED,false));return c;}
        c.addView(txt("Качество данных: "+m.reliability+"% · "+m.ph.source+" / "+m.pa.source+" · КФ: "+(m.oddSource.isEmpty()?"не найден":m.oddSource),10,m.reliability>=70?GREEN:AMBER,true));c.addView(section("ИСХОД (1X2)"));addMarket3(c,"П1",m.p1,m.p1Odd,"Х",m.px,m.xOdd,"П2",m.p2,m.p2Odd);
        c.addView(section("ТОТАЛЫ"));addMarket2(c,"ТБ 2,5",m.o25,m.o25Odd,"ТБ 3,5",m.o35,m.o35Odd);addMarket2(c,"ТМ 2,5",m.u25,m.u25Odd,"ТМ 3,5",m.u35,m.u35Odd);
        c.addView(section("ОБЕ ЗАБЬЮТ"));addMarket2(c,"ОЗ — ДА",m.bttsYes,m.bttsYesOdd,"ОЗ — НЕТ",m.bttsNo,m.bttsNoOdd);addMarket1(c,"ОЗ + ТБ 2,5",m.bttsO25,m.bttsO25Odd);
        c.addView(section("1-Й ТАЙМ"));addMarket3(c,"П1 (1Т)",m.hP1,m.hP1Odd,"Х (1Т)",m.hX,m.hXOdd,"П2 (1Т)",m.hP2,m.hP2Odd);addMarket3(c,"ТБ 0,5 (1Т)",m.hO05,m.hO05Odd,"ТБ 1,0 (1Т)",m.hO10,m.hO10Odd,"ТБ 1,5 (1Т)",m.hO15,m.hO15Odd);if(m.hPush10>=0)c.addView(txt("ТБ 1,0: вероятность возврата при одном голе — "+m.hPush10+"%",9,MUTED,false));
        TextView a=txt("Показать проверку критериев",11,ACCENT,true);a.setGravity(Gravity.CENTER);a.setPadding(0,dp(8),0,0);c.addView(a);a.setOnClickListener(x->toggleAudit(c,a,m));return c;}
    private TextView section(String s){TextView t=txt(s,11,ACCENT,true);t.setPadding(0,dp(9),0,dp(3));return t;}
    private void addMarket1(LinearLayout p,String a,int pa,double oa){if(oa>0&&oa<MIN_ODD)return;p.addView(marketBox(a,pa,oa),new LinearLayout.LayoutParams(-1,dp(72)));}
    private void addMarket2(LinearLayout p,String a,int pa,double oa,String b,int pb,double ob){LinearLayout r=new LinearLayout(this);r.setWeightSum(2);if(!(oa>0&&oa<MIN_ODD))r.addView(marketBox(a,pa,oa),new LinearLayout.LayoutParams(0,dp(72),1));else r.addView(blank(),new LinearLayout.LayoutParams(0,dp(72),1));if(!(ob>0&&ob<MIN_ODD))r.addView(marketBox(b,pb,ob),new LinearLayout.LayoutParams(0,dp(72),1));else r.addView(blank(),new LinearLayout.LayoutParams(0,dp(72),1));p.addView(r);}
    private void addMarket3(LinearLayout p,String a,int pa,double oa,String b,int pb,double ob,String c,int pc,double oc){LinearLayout r=new LinearLayout(this);r.setWeightSum(3);r.addView((oa>0&&oa<MIN_ODD)?blank():marketBox(a,pa,oa),new LinearLayout.LayoutParams(0,dp(76),1));r.addView((ob>0&&ob<MIN_ODD)?blank():marketBox(b,pb,ob),new LinearLayout.LayoutParams(0,dp(76),1));r.addView((oc>0&&oc<MIN_ODD)?blank():marketBox(c,pc,oc),new LinearLayout.LayoutParams(0,dp(76),1));p.addView(r);}
    private View marketBox(String label,int p,double odd){LinearLayout b=v();b.setGravity(Gravity.CENTER);b.setPadding(dp(3),dp(3),dp(3),dp(3));b.setBackground(box(CARD2,9));b.addView(txt(label,10,MUTED,true));b.addView(txt(p<0?"—":p+"%",14,p>=60?GREEN:(p>=45?AMBER:TEXT),true));b.addView(txt(odd>=MIN_ODD?"КФ "+String.format(Locale.US,"%.2f",odd):"КФ —",10,TEXT,true));if(p>=0&&odd>=MIN_ODD){double ev=p/100.0*odd-1;TextView e=txt("EV "+String.format(Locale.US,"%+.1f%%",ev*100),9,ev>0?GREEN:RED,true);b.addView(e);}return b;}private View blank(){LinearLayout x=v();return x;}
    private void toggleAudit(LinearLayout c,TextView ctl,Match m){Object tag=ctl.getTag();if(tag instanceof View){c.removeView((View)tag);ctl.setTag(null);return;}LinearLayout b=v();b.setPadding(dp(8),dp(8),dp(8),dp(8));b.setBackground(box(CARD2,10));for(Criterion x:m.criteria){LinearLayout r=new LinearLayout(this);LinearLayout l=v();l.addView(txt(x.name,10,x.ok?TEXT:MUTED,true));l.addView(txt(x.detail,9,MUTED,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));r.addView(txt(x.ok?"вес "+String.format(Locale.US,"%.1f",x.w):"—",9,x.ok?GREEN:MUTED,true));b.addView(r);}c.addView(b);ctl.setTag(b);}

    private int findTeam(Object node,String name){int[]b={0,-1};walkTeam(node,name,b);return b[0];}private void walkTeam(Object node,String name,int[]b){if(node instanceof JSONObject){JSONObject o=(JSONObject)node,ent=o.optJSONObject("entity");if(ent!=null){String n=ent.optString("name","");JSONObject sp=ent.optJSONObject("sport");String slug=sp==null?"":sp.optString("slug","");if(slug.isEmpty()||slug.equals("football")){int s=similarity(name,n);if(s>b[1]){b[0]=ent.optInt("id",0);b[1]=s;}}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkTeam(v,name,b);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkTeam(v,name,b);}}}
    private int findFot(Object node,String name){int[]b={0,-1};walkFindFot(node,name,b);return b[0];}private void walkFindFot(Object node,String name,int[]b){if(node instanceof JSONObject){JSONObject o=(JSONObject)node;String n=o.optString("name",o.optString("title",""));int id=o.optInt("teamId",o.optInt("id",0));String type=o.optString("type",o.optString("suggestionType",""));if(id>0&&!n.isEmpty()&&(type.toLowerCase(Locale.ROOT).contains("team")||o.has("teamId"))){int s=similarity(name,n);if(s>b[1]){b[0]=id;b[1]=s;}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkFindFot(v,name,b);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkFindFot(v,name,b);}}}
    private void walkFot(Object node,int id,Profile p){if(p.n>=20)return;if(node instanceof JSONObject){JSONObject o=(JSONObject)node,h=o.optJSONObject("home"),a=o.optJSONObject("away");if(h!=null&&a!=null){int hi=h.optInt("id",0),ai=a.optInt("id",0);if(hi==id||ai==id){JSONObject st=o.optJSONObject("status");String ss=st==null?"":st.optString("scoreStr","");int[]sc=scorePair(ss);if(sc!=null){Hist x=new Hist();x.home=hi==id;x.gf=x.home?sc[0]:sc[1];x.ga=x.home?sc[1]:sc[0];p.add(x);}}}Iterator<String>it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof JSONObject||v instanceof JSONArray)walkFot(v,id,p);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length()&&p.n<20;i++){Object v=a.opt(i);if(v instanceof JSONObject||v instanceof JSONArray)walkFot(v,id,p);}}}

    private void sortMatches(List<Match> x){Collections.sort(x,new Comparator<Match>(){public int compare(Match a,Match b){int pa=priority(a),pb=priority(b);if(pa!=pb)return Integer.compare(pa,pb);int c=a.country.compareTo(b.country);if(c!=0)return c;c=a.league.compareTo(b.league);if(c!=0)return c;return Long.compare(a.ts,b.ts);}});}private int priority(Match m){String s=norm(m.country+" "+m.league);String[] top={"лига чемпионов","лига европы","премьер лига","ла лига","серия а","бундеслига","лига 1","чемпионат мира","евро"};for(int i=0;i<top.length;i++)if(s.contains(norm(top[i])))return i;return 100;}
    private void dedupe(List<Match>x){Map<String,Match>m=new LinkedHashMap<>();for(Match a:x)m.put(a.id,a);x.clear();x.addAll(m.values());}private List<Match> cloneList(List<Match>x){List<Match>o=new ArrayList<>();for(Match a:x)o.add(a.copy());return o;}
    private boolean matchesQuery(Match m,String q){String all=norm(m.rawHome+" "+m.rawAway+" "+m.home+" "+m.away+" "+m.country+" "+m.league),k=norm(q);return all.contains(k)||tokenHit(all,k);}private boolean tokenHit(String all,String q){for(String t:q.split(" "))if(t.length()>2&&!all.contains(t))return false;return true;}
    private boolean excluded(String s){String x=norm(s).replace('×','x');String[]bad={"3x3","4x4","5x5","6x6","7x7","8x8","futsal","футзал","мини футбол","indoor","cyber","кибер","esport","virtual","виртуал","penalty shootout"};for(String b:bad)if(x.contains(norm(b)))return true;return false;}
    private int findMinute(JSONObject e){JSONObject tm=e.optJSONObject("time");JSONObject st=e.optJSONObject("status");String desc=st==null?"":st.optString("description","").toLowerCase(Locale.ROOT);if(tm!=null){long start=tm.optLong("currentPeriodStartTimestamp",0);if(start>0){int base=(desc.contains("second")||desc.contains("2nd"))?45:0;int v=base+(int)Math.max(0,(System.currentTimeMillis()/1000-start)/60);if(v<=125)return v;}}return e.optInt("minute",0);}
    private int scoreVal(JSONObject s){if(s==null)return-1;if(s.has("normaltime"))return s.optInt("normaltime",-1);return s.optInt("current",-1);}private int[]scorePair(String s){java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d+)\\s*[:\\-]\\s*(\\d+)").matcher(s==null?"":s);return m.find()?new int[]{Integer.parseInt(m.group(1)),Integer.parseInt(m.group(2))}:null;}
    private JSONObject getJson(String u,String ref)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(7000);c.setReadTimeout(10000);c.setRequestProperty("Accept","application/json, text/plain, */*");c.setRequestProperty("Accept-Language","ru-RU,ru;q=0.9,en;q=0.6");c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36");if(ref!=null)c.setRequestProperty("Referer",ref);int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String body=read(is);c.disconnect();if(code<200||code>=300)throw new Exception("HTTP "+code);if(body.trim().isEmpty())throw new Exception("пустой ответ");return new JSONObject(body);}private String read(InputStream is)throws Exception{if(is==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(is));StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s);r.close();return b.toString();}
    private String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}private boolean truth(Object o){String s=String.valueOf(o);return"1".equals(s)||"true".equalsIgnoreCase(s)||"yes".equalsIgnoreCase(s);}private double num(Object o){if(o==null)return 0;try{return Double.parseDouble(String.valueOf(o).replace("%","").replace(',','.').replaceAll("[^0-9.\\-]",""));}catch(Exception e){return 0;}}private double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));}private int similarity(String a,String b){String x=norm(a),y=norm(b);if(x.equals(y))return 100;if(x.contains(y)||y.contains(x))return 80;int s=0;for(String t:x.split(" "))if(t.length()>2&&y.contains(t))s+=20;return s;}private String norm(String s){return s==null?"":s.toLowerCase(Locale.ROOT).replace('ё','е').replaceAll("[^\\p{L}\\p{N}]+"," ").trim();}
    private String ruCountry(String s){String k=norm(s);if(k.contains("netherlands"))return"Нидерланды";if(k.contains("england"))return"Англия";if(k.contains("spain"))return"Испания";if(k.contains("italy"))return"Италия";if(k.contains("germany"))return"Германия";if(k.contains("france"))return"Франция";if(k.contains("russia"))return"Россия";if(k.contains("turkey"))return"Турция";if(k.contains("portugal"))return"Португалия";if(k.contains("belgium"))return"Бельгия";if(k.contains("brazil"))return"Бразилия";if(k.contains("argentina"))return"Аргентина";if(k.contains("finland"))return"Финляндия";if(k.contains("sweden"))return"Швеция";if(k.contains("norway"))return"Норвегия";if(k.contains("denmark"))return"Дания";if(k.contains("ukraine"))return"Украина";return ru(s);}private String ruLeague(String s){String k=norm(s);if(k.contains("eerste divisie"))return"Первый дивизион";if(k.contains("premier league"))return"Премьер-лига";if(k.contains("champions league"))return"Лига чемпионов";if(k.contains("europa league"))return"Лига Европы";if(k.contains("conference league"))return"Лига конференций";if(k.contains("la liga"))return"Ла Лига";if(k.contains("serie a"))return"Серия А";if(k.contains("bundesliga"))return"Бундеслига";if(k.contains("ligue 1"))return"Лига 1";return ru(s);}private String ru(String s){if(s==null)return"";if(!s.matches(".*[A-Za-z].*"))return s;String x=s;String[][]r={{"PSV","ПСВ"},{"AZ","АЗ"},{"FC","ФК"},{"United","Юнайтед"},{"City","Сити"},{"Real","Реал"},{"Inter","Интер"},{"Milan","Милан"},{"Juventus","Ювентус"},{"Barcelona","Барселона"},{"Madrid","Мадрид"},{"Munich","Мюнхен"},{"Dortmund","Дортмунд"},{"Netherlands","Нидерланды"}};for(String[]p:r)x=x.replace(p[0],p[1]);return x;}
    private String dateTime(long ts){return ts<=0?"—":new SimpleDateFormat("dd.MM HH:mm",Locale.getDefault()).format(new Date(ts*1000));}private String f1(double x){return String.format(Locale.US,"%.1f",x);}private String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    private LinearLayout v(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private Button tab(String s,boolean on){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(box(on?ACCENT:CARD2,11));return b;}private TextView txt(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}

    static class OddCandidate{int score=0;Match m;}
    static class Hist{int id,gf,ga,h1gf=-1,h1ga=-1;boolean home;}
    static class Profile{String source="";long loadedAt;int n,w,d,l,homeN,awayN,h1N;double gf,ga,homeGF,homeGA,awayGF,awayGA,h1GF,h1GA,xgF,xgA,sotF,sotA,shF,shA,posF,posA,corF,corA,cardF,cardA;int xgN,sotN,shN,posN,corN,cardN,statN;void add(Hist h){if(n>=20)return;n++;gf+=h.gf;ga+=h.ga;if(h.gf>h.ga)w++;else if(h.gf==h.ga)d++;else l++;if(h.home){homeN++;homeGF+=h.gf;homeGA+=h.ga;}else{awayN++;awayGF+=h.gf;awayGA+=h.ga;}if(h.h1gf>=0&&h.h1ga>=0){h1N++;h1GF+=h.h1gf;h1GA+=h.h1ga;}}double gf(){return n>0?gf/n:1.2;}double ga(){return n>0?ga/n:1.2;}double form(){return n>0?(3.0*w+d)/(3.0*n):.5;}double homeGF(){return homeN>0?homeGF/homeN:gf();}double homeGA(){return homeN>0?homeGA/homeN:ga();}double awayGF(){return awayN>0?awayGF/awayN:gf();}double awayGA(){return awayN>0?awayGA/awayN:ga();}double h1gf(){return h1N>0?h1GF/h1N:gf()*.46;}double h1ga(){return h1N>0?h1GA/h1N:ga()*.46;}double xgF(){return xgN>0?xgF/xgN:0;}double xgA(){return xgN>0?xgA/xgN:0;}double sotF(){return sotN>0?sotF/sotN:0;}double sotA(){return sotN>0?sotA/sotN:0;}double shF(){return shN>0?shF/shN:0;}double shA(){return shN>0?shA/shN:0;}double posF(){return posN>0?posF/posN:0;}double corF(){return corN>0?corF/corN:0;}double corA(){return corN>0?corA/corN:0;}double cardF(){return cardN>0?cardF/cardN:0;}double cardA(){return cardN>0?cardA/cardN:0;}}
    static class Criterion{String name,detail;boolean ok;double w,lh,la;Criterion(String n,boolean o,double w,double lh,double la,String d){name=n;ok=o;this.w=w;this.lh=lh;this.la=la;detail=d;}}
    static class Match{String id="",country="Прочее",league="",home="",away="",rawHome="",rawAway="",error="",oddSource="";long ts;boolean live=false,loading=false,ready=false;int min=0,hg=-1,ag=-1,p1=-1,px=-1,p2=-1,reliability=0,o15=-1,u15=-1,o25=-1,u25=-1,o35=-1,u35=-1,bttsYes=-1,bttsNo=-1,bttsO25=-1,hP1=-1,hX=-1,hP2=-1,hO05=-1,hO10=-1,hPush10=-1,hO15=-1;double p1Odd,xOdd,p2Odd,o15Odd,u15Odd,o25Odd,u25Odd,o35Odd,u35Odd,bttsYesOdd,bttsNoOdd,bttsO25Odd,hP1Odd,hXOdd,hP2Odd,hO05Odd,hU05Odd,hO10Odd,hU10Odd,hO15Odd,hU15Odd,liveXgH,liveXgA,liveSotH,liveSotA,liveShotsH,liveShotsA,lambdaH,lambdaA;Profile ph,pa;final List<Criterion>criteria=new ArrayList<>();Match copy(){Match m=new Match();m.id=id;m.country=country;m.league=league;m.home=home;m.away=away;m.rawHome=rawHome;m.rawAway=rawAway;m.ts=ts;m.live=live;m.min=min;m.hg=hg;m.ag=ag;return m;}}
    private void copyOdds(Match a,Match b){b.p1Odd=a.p1Odd;b.xOdd=a.xOdd;b.p2Odd=a.p2Odd;b.o15Odd=a.o15Odd;b.u15Odd=a.u15Odd;b.o25Odd=a.o25Odd;b.u25Odd=a.u25Odd;b.o35Odd=a.o35Odd;b.u35Odd=a.u35Odd;b.bttsYesOdd=a.bttsYesOdd;b.bttsNoOdd=a.bttsNoOdd;b.bttsO25Odd=a.bttsO25Odd;b.hP1Odd=a.hP1Odd;b.hXOdd=a.hXOdd;b.hP2Odd=a.hP2Odd;b.hO05Odd=a.hO05Odd;b.hU05Odd=a.hU05Odd;b.hO10Odd=a.hO10Odd;b.hU10Odd=a.hU10Odd;b.hO15Odd=a.hO15Odd;b.hU15Odd=a.hU15Odd;}
}
